/**
 * Forensics analysis — verdicts, retry forensics, Flakiness Leaderboard,
 * FLAKY.md artifact generation (Master Plan R4).
 *
 * Core fact: a test that passes only on attempt >= 2 is not a passing
 * test — it is a lucky test. It gets flagged as TRUE-FLAKE regardless of
 * the final green checkmark.
 */

import type {
  ForensicsReport,
  RunStatus,
  TestRecord,
  TestVerdict,
} from "./types.js";

const MAX_RECORDS = 100_000;

export function analyze(
  records: TestRecord[],
  source: ForensicsReport["source"],
): ForensicsReport {
  const verdicts: TestVerdict[] = [];
  let failed = 0;
  let skipped = 0;
  let retried = 0;
  let flaky = 0;
  let totalDuration = 0;

  for (const rec of records.slice(0, MAX_RECORDS)) {
    const attempts = rec.attempts;
    const last = attempts[attempts.length - 1];
    const finalStatus: RunStatus = last?.status ?? "skipped";
    const totalDurationMs = attempts.reduce((s, a) => s + a.durationMs, 0);
    totalDuration += totalDurationMs;

    const everFailed = attempts.some(
      (a) => a.status === "failed" || a.status === "timedOut",
    );
    const passedOnRetry =
      finalStatus === "passed" && attempts.length >= 2 && everFailed;

    if (
      finalStatus === "failed" ||
      finalStatus === "timedOut" ||
      finalStatus === "interrupted"
    )
      failed++;
    if (finalStatus === "skipped") skipped++;
    if (attempts.length >= 2) retried++;
    if (passedOnRetry) flaky++;

    verdicts.push({
      file: rec.file,
      title: rec.title,
      attempts: attempts.length,
      finalStatus,
      totalDurationMs,
      passedOnRetry,
      everFailed,
      skipped: finalStatus === "skipped",
    });
  }

  return {
    source,
    totalTests: verdicts.length,
    failed,
    skipped,
    retriedTests: retried,
    flakyTests: flaky,
    totalDurationMs: totalDuration,
    verdicts,
  };
}

/** Flakiness Leaderboard: flakiest first, then slowest. */
export function leaderboard(report: ForensicsReport): TestVerdict[] {
  return [...report.verdicts]
    .filter((v) => v.passedOnRetry || v.everFailed)
    .sort((a, b) => {
      if (a.passedOnRetry !== b.passedOnRetry) return a.passedOnRetry ? -1 : 1;
      if (a.attempts !== b.attempts) return b.attempts - a.attempts;
      return b.totalDurationMs - a.totalDurationMs;
    })
    .slice(0, 25);
}

function bar(ms: number, maxMs: number, width = 20): string {
  if (maxMs <= 0) return "";
  const filled = Math.round((ms / maxMs) * width);
  return (
    "█".repeat(Math.min(width, filled)) +
    "░".repeat(Math.max(0, width - filled))
  );
}

export function renderLeaderboard(report: ForensicsReport): string {
  const lines: string[] = [];
  lines.push("▚▞ FLAKINESS LEADERBOARD");
  lines.push("");
  lines.push(
    `${report.totalTests} tests · ${report.failed} failed · ${report.flakyTests} flaky · ${report.retriedTests} retried`,
  );
  lines.push("");

  const top = leaderboard(report);
  if (top.length === 0) {
    lines.push("No failures or retries found — nothing suspicious this run.");
    return lines.join("\n");
  }

  const maxMs = Math.max(...top.map((v) => v.totalDurationMs), 1);
  for (const v of top) {
    const flag = v.passedOnRetry
      ? "TRUE-FLAKE"
      : v.finalStatus === "passed"
        ? "retried"
        : "FAILING";
    lines.push(
      `${flag.padEnd(10)} ${v.title} (${v.file})`,
      `           ${bar(v.totalDurationMs, maxMs)} ${(v.totalDurationMs / 1000).toFixed(1)}s · ${v.attempts} attempt${v.attempts === 1 ? "" : "s"}`,
    );
  }
  return lines.join("\n");
}

/** FLAKY.md — the committed artifact. */
export function renderFlakyMd(report: ForensicsReport): string {
  const lines: string[] = [];
  lines.push("# FLAKY.md");
  lines.push("");
  lines.push(
    `> Generated by mjolnir forensics from ${report.source} run data.`,
  );
  lines.push(
    "> A test that passes only on retry is not a passing test — it is a lucky test.",
  );
  lines.push("");
  lines.push(
    `**${report.totalTests}** tests analyzed · **${report.flakyTests}** true flakes · **${report.retriedTests}** retried · **${report.failed}** failing`,
  );
  lines.push("");

  const top = leaderboard(report);
  if (top.length === 0) {
    lines.push("_No flaky or failing tests detected in this run._");
    return lines.join("\n");
  }

  lines.push("| Status | Test | File | Attempts | Duration |");
  lines.push("|--------|------|------|----------|----------|");
  for (const v of top) {
    const status = v.passedOnRetry
      ? "🔥 TRUE-FLAKE"
      : v.finalStatus === "passed"
        ? "↻ retried"
        : "❌ failing";
    lines.push(
      `| ${status} | \`${v.title}\` | \`${v.file}\` | ${v.attempts} | ${(v.totalDurationMs / 1000).toFixed(1)}s |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}
