/**
 * `mjolnir triage` — the Triage Meeting Killer (Tier 5 #22).
 *
 * Consumes a forensics report and generates TRIAGE.md: the artifact that
 * turns a 45-minute flaky-test meeting into 10 minutes of approvals.
 *
 * Quarantine proposal rule (deterministic, documented):
 *   propose quarantine when attempts >= 2 AND everFailed
 *   priority: TRUE-FLAKE first, then most attempts, then slowest.
 */

import type { ForensicsReport, TestVerdict } from "./types.js";
import { FLAKE_GLYPH, sectionHeader, plainContext } from "../reporter/ui.js";

const ui = plainContext();

export interface TriageRow {
  file: string;
  title: string;
  attempts: number;
  passedOnRetry: boolean;
  finalStatus: TestVerdict["finalStatus"];
  totalDurationMs: number;
  suggestedAction: string;
  proposedQuarantine: boolean;
}

const QUARANTINE_MIN_ATTEMPTS = 2;

/** Deterministic triage table rows, worst first. */
export function triageRows(report: ForensicsReport): TriageRow[] {
  return report.verdicts
    .filter((v) => v.everFailed || v.passedOnRetry)
    .sort((a, b) => {
      if (a.passedOnRetry !== b.passedOnRetry) return a.passedOnRetry ? -1 : 1;
      if (a.attempts !== b.attempts) return b.attempts - a.attempts;
      return b.totalDurationMs - a.totalDurationMs;
    })
    .map((v) => ({
      file: v.file,
      title: v.title,
      attempts: v.attempts,
      passedOnRetry: v.passedOnRetry,
      finalStatus: v.finalStatus,
      totalDurationMs: v.totalDurationMs,
      suggestedAction: suggestAction(v),
      proposedQuarantine: v.attempts >= QUARANTINE_MIN_ATTEMPTS && v.everFailed,
    }));
}

function suggestAction(v: TestVerdict): string {
  if (v.passedOnRetry && v.attempts >= QUARANTINE_MIN_ATTEMPTS)
    return "quarantine + ticket";
  if (v.passedOnRetry) return "fix nondeterminism";
  if (v.finalStatus === "failed" || v.finalStatus === "timedOut")
    return "fix now — failing";
  return "investigate";
}

/** Terminal rendering of the triage proposal. */
export function renderTriage(report: ForensicsReport): string {
  const rows = triageRows(report);
  const lines: string[] = [];
  lines.push(sectionHeader("FLAKY TRIAGE — auto-generated, do not edit", ui));
  lines.push("");
  if (rows.length === 0) {
    lines.push("Nothing to triage — no failures or retries in this run.");
    return lines.join("\n");
  }
  const quarantineCount = rows.filter((r) => r.proposedQuarantine).length;
  for (const r of rows) {
    const flag = r.passedOnRetry ? "TRUE-FLAKE" : "FAILING";
    lines.push(
      `• [${flag}] ${r.title} (${r.file}) — ${r.attempts} attempt${r.attempts === 1 ? "" : "s"} → ${r.suggestedAction}`,
    );
  }
  lines.push("");
  lines.push(
    `Auto-quarantine proposal: ${quarantineCount} test${quarantineCount === 1 ? "" : "s"} (retried ≥${QUARANTINE_MIN_ATTEMPTS} and failed at least once).`,
  );
  lines.push(
    "Quarantined tests should run nightly, not per-PR — quarantine is not deletion.",
  );
  return lines.join("\n");
}

/** TRIAGE.md — the meeting artifact. */
export function renderTriageMd(report: ForensicsReport): string {
  const rows = triageRows(report);
  const lines: string[] = [];
  lines.push("# TRIAGE.md");
  lines.push("");
  lines.push(
    "> Auto-generated by `mjolnir triage` from real run data. Do not edit by hand.",
  );
  lines.push("");
  if (rows.length === 0) {
    lines.push("_No flaky or failing tests this run — nothing to triage._ 🎉");
    return lines.join("\n");
  }
  lines.push(
    "| Status | Test | File | Attempts | Duration | Suggested action | Quarantine? |",
  );
  lines.push(
    "|--------|------|------|----------|----------|------------------|-------------|",
  );
  for (const r of rows) {
    const status = r.passedOnRetry ? `${FLAKE_GLYPH} TRUE-FLAKE` : "❌ FAILING";
    lines.push(
      `| ${status} | \`${r.title}\` | \`${r.file}\` | ${r.attempts} | ${(r.totalDurationMs / 1000).toFixed(1)}s | ${r.suggestedAction} | ${r.proposedQuarantine ? "✅ propose" : "—"} |`,
    );
  }
  const q = rows.filter((r) => r.proposedQuarantine).length;
  lines.push("");
  lines.push(
    `**Auto-quarantine proposal: ${q}** — move them to the nightly suite and open tracked tickets.`,
  );
  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// triage v2 (Mega MVP Master Plan v3.1 §26 WI-8, §9): the GUIDED WORKFLOW.
//
// FAILED → CLASSIFY → COLLECT EVIDENCE → CORRELATE → TRUST VERDICT →
// NEXT ACTION → FIX → RERUN → PROOF
//
// Deterministic, non-TTY-dependent, --json for agents. The acceptance
// law: EVERY row ends with a concrete next action — a triage row
// without one is a dump, not a workflow.
// ---------------------------------------------------------------------------

/**
 * Forensic classification vocabulary (0.6.x, §9 CLASSIFY step). This is
 * the triage-domain classification — deliberately NOT the 1.1.x
 * forensic verdict taxonomy (WI-18: REAL/ENVIRONMENTAL/INFRASTRUCTURE/
 * INCONCLUSIVE + contradiction handling). WI-18 will extend this map;
 * the 0.6.x labels stay stable for artifact consumers.
 */
export type TriageClass =
  | "RETRY-DEPENDENT" // failed then passed on retry — flake behavior
  | "FAILING" // failed on the final attempt
  | "TIMEOUT" // final attempt timed out
  | "SKIPPED"; // skipped after retries (failed-then-skipped harness behavior)

/** CLASSIFY — deterministic from the verdict's retry history. */
export function classifyVerdict(v: TestVerdict): TriageClass {
  if (v.passedOnRetry) return "RETRY-DEPENDENT";
  if (v.finalStatus === "timedOut") return "TIMEOUT";
  if (v.finalStatus === "failed") return "FAILING";
  return "SKIPPED";
}

/** COLLECT EVIDENCE — the facts the classification stands on. */
export function evidenceFor(v: TestVerdict): string[] {
  const ev: string[] = [];
  ev.push(`${v.attempts} attempt(s), final status ${v.finalStatus}`);
  if (v.everFailed) ev.push("failed at least once");
  if (v.passedOnRetry) ev.push("passed only on retry (attempt >= 2)");
  ev.push(`total ${(v.totalDurationMs / 1000).toFixed(1)}s`);
  return ev;
}

/**
 * TRUST VERDICT — how much the run evidence alone supports acting on
 * this row. Static-ladder semantics do NOT apply here (no findings
 * involved); the run's own history is the evidence.
 */
export function trustVerdictFor(v: TestVerdict): string {
  const c = classifyVerdict(v);
  switch (c) {
    case "RETRY-DEPENDENT":
      return "HIGH — the run itself demonstrates the flake (failed, then passed)";
    case "TIMEOUT":
      return "MEDIUM — timeout is real; environmental slowness vs. real hang not distinguished yet";
    case "FAILING":
      return "HIGH — deterministic final failure";
    case "SKIPPED":
      return "LOW — skipped after retries; intent unclear";
  }
}

/**
 * NEXT ACTION — concrete, re-runnable, always present (the WI-8
 * acceptance law). Trace collection advice is the 1.1.x hook (WI-17):
 * today the honest command set is repeat/compare/inspect, not
 * "collect a trace", because trace.zip is not yet ingested.
 */
function safeTriageText(value: string): string {
  return value.replace(/[;&|`$()\\\r\n]/g, " ").slice(0, 200);
}

export function nextActionFor(v: TestVerdict): string {
  const c = classifyVerdict(v);
  switch (c) {
    case "RETRY-DEPENDENT":
      return `repeat execution of this test (3+ runs) to confirm the flake rate, then quarantine + ticket: ${safeTriageText(v.file)}`;
    case "TIMEOUT":
      return `re-run this test in isolation with a 60-second timeout to separate slowness from a hang: ${safeTriageText(v.file)}`;
    case "FAILING":
      return `reproduce this test in isolation, then fix and re-run: ${safeTriageText(v.file)} — ${safeTriageText(v.title)}`;
    case "SKIPPED":
      return `inspect the skip condition in ${safeTriageText(v.file)} — a skip after a failure usually hides an environment problem`;
  }
}

/** The full guided-workflow row for one verdict. */
export interface TriageWorkflowRow {
  test: string;
  file: string;
  classification: TriageClass;
  evidence: string[];
  trustVerdict: string;
  nextAction: string;
  proposedQuarantine: boolean;
}

/** Deterministic guided rows, worst first (same order law as triageRows). */
export function workflowRows(report: ForensicsReport): TriageWorkflowRow[] {
  return report.verdicts
    .filter((v) => v.everFailed || v.passedOnRetry || v.skipped)
    .sort((a, b) => {
      if (a.passedOnRetry !== b.passedOnRetry) return a.passedOnRetry ? -1 : 1;
      if (a.attempts !== b.attempts) return b.attempts - a.attempts;
      return b.totalDurationMs - a.totalDurationMs;
    })
    .map((v) => {
      const classification = classifyVerdict(v);
      return {
        test: v.title,
        file: v.file,
        classification,
        evidence: evidenceFor(v),
        trustVerdict: trustVerdictFor(v),
        nextAction: nextActionFor(v),
        proposedQuarantine:
          v.attempts >= QUARANTINE_MIN_ATTEMPTS && v.everFailed,
      };
    });
}

/** Terminal rendering of the guided workflow. */
export function renderTriageWorkflow(report: ForensicsReport): string {
  const rows = workflowRows(report);
  const lines: string[] = [];
  lines.push(
    sectionHeader("TRIAGE WORKFLOW — guided, one row = one next action", ui),
  );
  lines.push("");
  if (rows.length === 0) {
    lines.push(
      "Nothing to triage — no failures, timeouts, or retries in this run.",
    );
    return lines.join("\n");
  }
  for (const r of rows) {
    // Vocabulary continuity: TRUE-FLAKE/FAILING are the established
    // forensic flags (forensics/analyze.ts) — the guided workflow's
    // classification refines them, never renames them.
    const flag =
      r.classification === "RETRY-DEPENDENT"
        ? "TRUE-FLAKE"
        : r.classification === "FAILING"
          ? "FAILING"
          : undefined;
    lines.push(
      `[${r.classification}${flag ? ` · ${flag}` : ""}] ${safeTriageText(r.test)} (${safeTriageText(r.file)})`,
    );
    for (const e of r.evidence) lines.push(`    evidence: ${e}`);
    lines.push(`    trust:    ${r.trustVerdict}`);
    lines.push(`    next:     ${r.nextAction}`);
    lines.push("");
  }
  const q = rows.filter((r) => r.proposedQuarantine).length;
  lines.push(
    `Auto-quarantine proposal: ${q} test(s) (retried ≥${QUARANTINE_MIN_ATTEMPTS} and failed at least once).`,
  );
  lines.push(
    "Rerun after fixes: the SAME command re-runs the SAME suite — proof is the changed second report.",
  );
  return lines.join("\n");
}

export interface TriageInteractiveOptions {
  /** Force interactive mode even without TTY (for testing). */
  force?: boolean;
  /** Pre-supplied answers (for testing): index → "y"/"n"/"i". */
  answers?: Map<number, "y" | "n" | "i">;
  /** Max rows to process in interactive mode. */
  maxRows?: number;
}

export interface TriageDecision {
  index: number;
  title: string;
  file: string;
  classification: TriageClass;
  action: "quarantine" | "fix" | "ignore";
  note: string;
}

/**
 * Interactive triage wizard — walks through triage rows one by
 * one: "Quarantine this? (y=quarantine, n=fix, i=ignore)".
 *
 * Without a TTY (CI, pipes) this mode degrades to a hint:
 * it prints what it would do and returns the rows for
 * `--json` consumption.
 */
export function triageInteractive(
  report: ForensicsReport,
  options: TriageInteractiveOptions = {},
): {
  decisions: TriageDecision[];
  mode: "interactive" | "guided";
  note?: string;
} {
  const rows = workflowRows(report);
  if (rows.length === 0) {
    return { decisions: [], mode: "guided", note: "Nothing to triage" };
  }

  // TTY check: without a terminal, we can't do true interactive.
  const hasTty = (process.stdout.isTTY ?? false) || options.force;
  if (!hasTty) {
    return {
      decisions: [],
      mode: "guided",
      note: "Interactive mode requires a TTY. Run without --interactive for the guided workflow, or use --json for agent consumption.",
    };
  }

  const decisions: TriageDecision[] = [];
  const maxRows = options.maxRows ?? rows.length;
  const answered = new Set<number>();

  for (let i = 0; i < Math.min(rows.length, maxRows); i++) {
    const r = rows[i];
    const answer = options.answers?.get(i);

    let action: TriageDecision["action"];
    let note: string;

    if (answer === "y") {
      action = "quarantine";
      note = "User chose quarantine via interactive prompt";
    } else if (answer === "n") {
      action = "fix";
      note = "User chose to fix directly";
    } else if (answer === "i") {
      action = "ignore";
      note = "User chose to ignore for now";
    } else if (r?.proposedQuarantine) {
      action = "quarantine";
      note =
        "Auto-proposed (retried ≥2 and failed) — confirm with --interactive";
    } else if (
      r &&
      (r.classification === "FAILING" || r.classification === "TIMEOUT")
    ) {
      action = "fix";
      note = "Auto-proposed: deterministic failure needs a fix";
    } else {
      action = "ignore";
      note = "Auto-proposed: not actionable";
    }

    decisions.push({
      index: i,
      title: r?.test ?? "",
      file: r?.file ?? "",
      classification: r?.classification ?? "SKIPPED",
      action,
      note,
    });
    answered.add(i);
  }

  return { decisions, mode: "interactive" };
}

/**
 * Generate quarantine proposals in interactive format.
 * Returns the proposal text and a machine-readable decision list.
 */
export function renderInteractiveProposals(
  report: ForensicsReport,
  options: TriageInteractiveOptions = {},
): string {
  const { decisions, mode, note } = triageInteractive(report, options);
  const lines: string[] = [];
  lines.push(sectionHeader("INTERACTIVE TRIAGE", ui));
  lines.push("");

  if (mode === "guided") {
    lines.push(note ?? "No interactive mode available.");
    lines.push("");
    lines.push("Run `mjolnir triage --json` for agent consumption,");
    lines.push("or run interactively in a terminal for guided decisions.");
    return lines.join("\n");
  }

  for (const d of decisions) {
    const icon =
      d.action === "quarantine" ? "🔒" : d.action === "fix" ? "🔧" : "⏭";
    const flag =
      d.classification === "RETRY-DEPENDENT" ? "TRUE-FLAKE" : d.classification;
    lines.push(
      `${icon} [${flag}] ${d.title} (${d.file}) → ${d.action.toUpperCase()}`,
    );
    lines.push(`   Note: ${d.note}`);
    lines.push("");
  }

  lines.push("To execute: review decisions and run `mjolnir triage --apply`.");
  return lines.join("\n");
}

/** --json twin of the guided workflow (agent-consumable). */
export function renderTriageWorkflowJson(report: ForensicsReport): string {
  return (
    JSON.stringify(
      {
        artifact: "mjolnir-triage-workflow",
        source: report.source,
        totalTests: report.totalTests,
        analysisComplete: report.analysisComplete,
        skippedReports: report.skippedReports,
        incompleteReasons: report.incompleteReasons,
        rows: workflowRows(report),
      },
      null,
      2,
    ) + "\n"
  );
}
