/**
 * `qa-doctor triage` — the Triage Meeting Killer (Tier 5 #22).
 *
 * Consumes a forensics report and generates TRIAGE.md: the artifact that
 * turns a 45-minute flaky-test meeting into 10 minutes of approvals.
 *
 * Quarantine proposal rule (deterministic, documented):
 *   propose quarantine when attempts >= 2 AND everFailed
 *   priority: TRUE-FLAKE first, then most attempts, then slowest.
 */

import type { ForensicsReport, TestVerdict } from "./types.js";

export interface TriageRow {
  file: string;
  title: string;
  attempts: number;
  passedOnRetry: boolean;
  finalStatus: TestVerdict["finalStatus"];
  totalDurationMs: number;
  suggestedAction: string;
  proposedQuarantine: boolean;
}

const QUARANTINE_MIN_ATTEMPTS = 2;

/** Deterministic triage table rows, worst first. */
export function triageRows(report: ForensicsReport): TriageRow[] {
  return report.verdicts
    .filter((v) => v.everFailed || v.passedOnRetry)
    .sort((a, b) => {
      if (a.passedOnRetry !== b.passedOnRetry) return a.passedOnRetry ? -1 : 1;
      if (a.attempts !== b.attempts) return b.attempts - a.attempts;
      return b.totalDurationMs - a.totalDurationMs;
    })
    .map((v) => ({
      file: v.file,
      title: v.title,
      attempts: v.attempts,
      passedOnRetry: v.passedOnRetry,
      finalStatus: v.finalStatus,
      totalDurationMs: v.totalDurationMs,
      suggestedAction: suggestAction(v),
      proposedQuarantine: v.attempts >= QUARANTINE_MIN_ATTEMPTS && v.everFailed,
    }));
}

function suggestAction(v: TestVerdict): string {
  if (v.passedOnRetry && v.attempts >= QUARANTINE_MIN_ATTEMPTS)
    return "quarantine + ticket";
  if (v.passedOnRetry) return "fix nondeterminism";
  if (v.finalStatus === "failed" || v.finalStatus === "timedOut")
    return "fix now — failing";
  return "investigate";
}

/** Terminal rendering of the triage proposal. */
export function renderTriage(report: ForensicsReport): string {
  const rows = triageRows(report);
  const lines: string[] = [];
  lines.push("▚▞ FLAKY TRIAGE — auto-generated, do not edit");
  lines.push("");
  if (rows.length === 0) {
    lines.push("Nothing to triage — no failures or retries in this run.");
    return lines.join("\n");
  }
  const quarantineCount = rows.filter((r) => r.proposedQuarantine).length;
  for (const r of rows) {
    const flag = r.passedOnRetry ? "TRUE-FLAKE" : "FAILING";
    lines.push(
      `• [${flag}] ${r.title} (${r.file}) — ${r.attempts} attempt${r.attempts === 1 ? "" : "s"} → ${r.suggestedAction}`,
    );
  }
  lines.push("");
  lines.push(
    `Auto-quarantine proposal: ${quarantineCount} test${quarantineCount === 1 ? "" : "s"} (retried ≥${QUARANTINE_MIN_ATTEMPTS} and failed at least once).`,
  );
  lines.push(
    "Quarantined tests should run nightly, not per-PR — quarantine is not deletion.",
  );
  return lines.join("\n");
}

/** TRIAGE.md — the meeting artifact. */
export function renderTriageMd(report: ForensicsReport): string {
  const rows = triageRows(report);
  const lines: string[] = [];
  lines.push("# TRIAGE.md");
  lines.push("");
  lines.push(
    "> Auto-generated by `mjolnir triage` from real run data. Do not edit by hand.",
  );
  lines.push("");
  if (rows.length === 0) {
    lines.push("_No flaky or failing tests this run — nothing to triage._ 🎉");
    return lines.join("\n");
  }
  lines.push(
    "| Status | Test | File | Attempts | Duration | Suggested action | Quarantine? |",
  );
  lines.push(
    "|--------|------|------|----------|----------|------------------|-------------|",
  );
  for (const r of rows) {
    const status = r.passedOnRetry ? "🔥 TRUE-FLAKE" : "❌ FAILING";
    lines.push(
      `| ${status} | \`${r.title}\` | \`${r.file}\` | ${r.attempts} | ${(r.totalDurationMs / 1000).toFixed(1)}s | ${r.suggestedAction} | ${r.proposedQuarantine ? "✅ propose" : "—"} |`,
    );
  }
  const q = rows.filter((r) => r.proposedQuarantine).length;
  lines.push("");
  lines.push(
    `**Auto-quarantine proposal: ${q}** — move them to the nightly suite and open tracked tickets.`,
  );
  lines.push("");
  return lines.join("\n");
}
