// GENERATED by `npm run fp-audit:generate` from tests/corpus/verdicts/*.jsonl.
// Do not edit by hand. tests/measured-fp-generated.spec.ts locks this to the verdicts.
//
// `fpRate` = FP / (TP + FP); `n` = classified (TP + FP) verdicts. A rule
// absent from this map has zero classified verdicts — it ships on assumption.

export interface MeasuredFp {
  /** FP / (TP + FP), 0..1. */
  fpRate: number;
  /** Number of hand-classified TP/FP verdicts behind the rate. */
  n: number;
}

export const MEASURED_FP: Readonly<Record<string, MeasuredFp>> = {
  "QA-CS-101": { fpRate: 0, n: 20 },
  "QA-CS-102": { fpRate: 0.65, n: 20 },
  "QA-CS-105": { fpRate: 0.25, n: 16 },
  "QA-CS-106": { fpRate: 1, n: 20 },
  "QA-CS-108": { fpRate: 1, n: 20 },
  "QA-CS-111": { fpRate: 1, n: 20 },
  "QA-JV-103": { fpRate: 0.5, n: 20 },
  "QA-JV-105": { fpRate: 0.1, n: 20 },
  "QA-JV-106": { fpRate: 1, n: 20 },
  "QA-JV-108": { fpRate: 1, n: 20 },
  "QA-JV-111": { fpRate: 1, n: 20 },
  "QA-PW-102": { fpRate: 1, n: 20 },
  "QA-PW-105": { fpRate: 1, n: 20 },
  "QA-PW-114": { fpRate: 1, n: 20 },
  "QA-PY-002": { fpRate: 0.05, n: 20 },
  "QA-PY-004": { fpRate: 0.45, n: 20 },
  "QA-PY-006": { fpRate: 1, n: 19 },
  "QA-PY-007": { fpRate: 0.65, n: 20 },
  "QA-TEST-003": { fpRate: 0.824, n: 17 },
};
