sonar.projectKey=Sergey-Bar_Mjolnir
sonar.organization=sergey-bar

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/fixtures/**,**/golden/**

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
