/**
 * README animated-demo asset reproducibility.
 *
 * Same contract as tests/hero-asset-reproducibility.spec.ts, for the
 * second README asset (assets/readme/demo.svg, the line-by-line animated
 * terminal). The asset is generated by `npm run docs:demo` from a real
 * scan of examples/demo-repo — this test makes drift from the current
 * reporter output fail CI instead of sitting undetected.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { runScan } from "../src/cli.js";
import { renderTerminal } from "../src/reporter/terminal.js";

const ROOT = join(import.meta.dirname, "..");
const DEMO_REPO = join(ROOT, "examples", "demo-repo");
const SVG_PATH = join(ROOT, "assets", "readme", "demo.svg");

async function scan() {
  return runScan({
    target: DEMO_REPO,
    json: false,
    verbose: false,
    maxDurationMs: Number.POSITIVE_INFINITY,
    scopeChanged: false,
    format: "terminal",
  });
}

describe("assets/readme/demo.svg reproducibility", () => {
  it("the README references the demo asset (a generated file no page shows is a maintained orphan)", () => {
    const readme = readFileSync(join(ROOT, "README.md"), "utf8");
    expect(readme).toContain("assets/readme/demo.svg");
  });

  it("the demo repo scan still produces findings (a stale/empty demo repo makes this test meaningless)", async () => {
    const result = await scan();
    expect(result.score).not.toBeNull();
    expect(result.findings.length).toBeGreaterThan(3);
  });

  it("the committed SVG contains every section header the current terminal reporter produces", async () => {
    const rendered = renderTerminal(await scan(), {
      isTTY: false,
      ascii: true,
    });
    const svg = readFileSync(SVG_PATH, "utf8");
    const sectionHeaders = rendered
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l.startsWith("▚ "));
    expect(sectionHeaders.length).toBeGreaterThan(0);
    for (const header of sectionHeaders) {
      const text = header.replace(/^▚\s*/, "");
      expect(
        svg,
        `demo asset is missing the "${text}" section the current reporter ` +
          `produces for this scan — regenerate with \`npm run docs:demo\`.`,
      ).toContain(text);
    }
  });

  it("every rule ID in the committed SVG actually fired in the current real scan", async () => {
    const result = await scan();
    const svg = readFileSync(SVG_PATH, "utf8");
    const realRuleIds = new Set(result.findings.map((f) => f.ruleId));
    const svgRuleIds = new Set(
      [...svg.matchAll(/QA-[A-Z]+-\d{3}/g)].map((m) => m[0]),
    );
    expect(svgRuleIds.size).toBeGreaterThan(0);
    for (const id of svgRuleIds) {
      expect(
        realRuleIds.has(id),
        `demo asset references ${id}, but the current real scan of ` +
          `examples/demo-repo does not produce that finding — regenerate ` +
          `with \`npm run docs:demo\`.`,
      ).toBe(true);
    }
  });

  it("the docs:demo script exists in package.json (regeneration is possible)", () => {
    const pkg = JSON.parse(
      readFileSync(join(ROOT, "package.json"), "utf8"),
    ) as {
      scripts: Record<string, string>;
    };
    expect(pkg.scripts["docs:demo"]).toBeDefined();
  });
});
