<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref } from "vue";
import { withBase } from "vitepress";
// A real, reproducible capture of the reporter's output — regenerated by
// `npm run docs:hero` and guarded by tests/hero-asset-reproducibility.spec.ts,
// so it can never drift from what the tool actually prints. Parsed out by
// site/scripts/gen-report.mjs. The gauge and the hero card read from here —
// this page states no number it did not get from a real scan (plan §1; D1
// was this file claiming 70 beside an asset that said 75).
import scan from "./generated/report.json";
import rulesData from "../../rules/rules.data.json";

/* ----- static, SSR-stable data ----------------------------------------- */

const ruleCount = rulesData.length;
const measuredCount = rulesData.filter((r) => r.measured).length;

const evidence = [
  {
    level: "E2",
    name: "Deterministic defect",
    body: "Structurally provable from the AST — a committed .only, an unawaited assertion. Full deduction.",
  },
  {
    level: "E1",
    name: "Heuristic pattern",
    body: "A strong, correctly-positioned signal — a regex-matched hard sleep. Half deduction, never claimed as proof.",
  },
  {
    level: "E0",
    name: "Observation",
    body: "Reported for context. Never gates CI, never moves the score.",
  },
];

const features = [
  {
    r: "ᛏ",
    title: "Worthiness Score",
    body: "One number, a transparent deduction table, no black box. Gate a pull request on it.",
    to: "/guide/scoring",
  },
  {
    r: "ᛗ",
    title: "Selector Health",
    body: "Grades your Playwright locators for resilience — not just whether the run went green.",
    to: "/guide/forensics#selector-health-score",
  },
  {
    r: "ᚦ",
    title: "Runtime Forensics",
    body: "Reads real Playwright & JUnit run data to catch TRUE-FLAKE, not a static guess.",
    to: "/guide/forensics",
  },
  {
    r: "ᚨ",
    title: "CI-Integrity Rules",
    body: "Catches continue-on-error, “|| true”, and every other trick that turns red pipelines green.",
    to: "/guide/ci",
  },
  {
    r: "ᛟ",
    title: "Four Languages, One Pass",
    body: "TypeScript, Python, Java and C#/.NET — plus pytest, JUnit / TestNG and CI workflows.",
    to: "/rules/",
  },
  {
    r: "ᛉ",
    title: "Local-First",
    body: "Zero network calls while scanning. Zero telemetry. The whole audit runs in seconds.",
    to: "/reference/exit-codes#trust-model",
  },
];

/**
 * MJÖLNIR in Elder Futhark: ᛗ(mannaz) ᛃ(jera) ᛟ(othala) ᛚ(laguz)
 * ᚾ(naudiz) ᛁ(isaz) ᚱ(raidho). Left-to-right in reading order, at
 * varied size and opacity so it reads as depth rather than a banner —
 * the word is there for anyone who looks, and never claimed for anyone
 * who doesn't. Positions are fixed, not random: the hero must render
 * identically on the server and the client.
 */
const runes = [
  { g: "ᛗ", x: 7, y: 22, s: 3.6, o: 0.15, d: 0 },
  { g: "ᛃ", x: 20, y: 68, s: 2.4, o: 0.1, d: 90 },
  { g: "ᛟ", x: 33, y: 14, s: 2.8, o: 0.12, d: 180 },
  { g: "ᛚ", x: 48, y: 78, s: 2.1, o: 0.09, d: 270 },
  { g: "ᚾ", x: 63, y: 30, s: 3.1, o: 0.13, d: 360 },
  { g: "ᛁ", x: 78, y: 72, s: 2.2, o: 0.1, d: 450 },
  { g: "ᚱ", x: 90, y: 20, s: 3.4, o: 0.14, d: 540 },
];

/* ----- animation (client only) --------------------------------------- */

const RING = 339.292; // 2πr, r = 54 — full offset = empty ring
/** Ring offset for a score: 0 = full ring, RING = empty. */
const offsetFor = (n: number) => RING * (1 - n / 100);

// Rendered (and served) at the real value, so the gauge is correct with
// no JS at all — an empty ring reading 0/100 would be exactly the kind of
// unearned number the site law forbids. The count-up resets it to zero in
// onMounted, only when there is actually a client to animate it.
const score = ref(scan.score);
const dash = ref(offsetFor(scan.score));
let io: IntersectionObserver | undefined;
let raf = 0;
let revealTimer = 0;

function settleGauge() {
  score.value = scan.score;
  dash.value = offsetFor(scan.score);
}

function runGauge() {
  const target = scan.score;
  const dur = 1500;
  const start = performance.now();
  const tick = (now: number) => {
    const p = Math.min(1, (now - start) / dur);
    const e = 1 - Math.pow(1 - p, 3);
    score.value = Math.round(e * target);
    dash.value = offsetFor(e * target);
    if (p < 1) raf = requestAnimationFrame(tick);
  };
  raf = requestAnimationFrame(tick);
}

const copied = ref(false);
async function copyCmd() {
  try {
    await navigator.clipboard.writeText("npx mjolnir-qa@latest");
    copied.value = true;
    setTimeout(() => (copied.value = false), 1600);
  } catch {
    /* clipboard blocked — no-op */
  }
}

function revealAll() {
  document
    .querySelectorAll("[data-reveal]")
    .forEach((el) => el.classList.add("is-in"));
  settleGauge();
}

onMounted(() => {
  const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  // No IntersectionObserver (or reduced motion): just show everything.
  if (!("IntersectionObserver" in window)) {
    revealAll();
    return;
  }

  // There is a client and it will animate, so wind the gauge back to zero
  // for the count-up. The gauge sits ~900px down, well below the fold, so
  // this never reads as a flicker.
  if (!reduce) {
    score.value = 0;
    dash.value = RING;
  }

  io = new IntersectionObserver(
    (entries) => {
      for (const en of entries) {
        if (!en.isIntersecting) continue;
        en.target.classList.add("is-in");
        if (en.target.hasAttribute("data-gauge") && !reduce) runGauge();
        else if (en.target.hasAttribute("data-gauge")) settleGauge();
        io?.unobserve(en.target);
      }
    },
    { threshold: 0.3 },
  );

  document.querySelectorAll("[data-reveal]").forEach((el) => io?.observe(el));

  // Safety net: never leave content stuck invisible.
  revealTimer = window.setTimeout(revealAll, 4000);
});

onBeforeUnmount(() => {
  io?.disconnect();
  cancelAnimationFrame(raf);
  clearTimeout(revealTimer);
});
</script>

<template>
  <main class="mj">
    <!-- ===================== HERO ===================== -->
    <section class="hero">
      <div class="hero-bg" aria-hidden="true">
        <div class="aurora" />
        <div class="forge-glow" />
        <!-- Not a scatter of decorative glyphs: read left to right, these
             are ᛗ ᛃ ᛟ ᛚ ᚾ ᛁ ᚱ — MJÖLNIR transliterated into Elder Futhark.
             Ordered, so it resolves into the word if you look; drifting at
             different depths, so it doesn't announce itself. -->
        <div class="runefield">
          <span
            v-for="r in runes"
            :key="r.g"
            class="rune"
            :style="{
              left: r.x + '%',
              top: r.y + '%',
              fontSize: r.s + 'rem',
              opacity: r.o,
              animationDelay: r.d + 'ms',
            }"
            >{{ r.g }}</span
          >
        </div>
        <svg class="bolt" viewBox="0 0 200 400" preserveAspectRatio="none">
          <path
            d="M120 -10 L70 150 L110 150 L60 410"
            fill="none"
            stroke="url(#boltgrad)"
            stroke-width="3"
          />
          <defs>
            <linearGradient id="boltgrad" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0" stop-color="#45c1d4" />
              <stop offset="1" stop-color="#e6bd57" />
            </linearGradient>
          </defs>
        </svg>
      </div>

      <div class="hero-inner">
        <h1 class="hero-logo">
          <img
            :src="withBase('/logo.webp')"
            alt="Mjölnir — Verification Trust Engine"
            width="720"
            height="360"
            fetchpriority="high"
          />
        </h1>
        <p class="lede">
          Your tests are lying to you.
          <span class="shimmer">We prove it.</span>
        </p>
        <p class="sub">
          Mjölnir audits test suites and CI pipelines, reports one worthiness
          score, and shows the exact places where trust breaks — across
          TypeScript, Python, Java, C# and your workflows.
        </p>

        <div class="cta-row">
          <a class="btn btn-primary" :href="withBase('/guide/getting-started')">
            Get started
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
              <path
                d="M3 8h9M8 3l5 5-5 5"
                stroke="currentColor"
                stroke-width="1.6"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </a>
          <a
            class="btn btn-ghost"
            href="https://github.com/Sergey-Bar/Mjolnir"
            target="_blank"
            rel="noreferrer"
          >
            <svg width="17" height="17" viewBox="0 0 16 16" fill="currentColor">
              <path
                d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"
              />
            </svg>
            Star on GitHub
          </a>
        </div>

        <button
          class="cmd"
          :class="{ copied }"
          type="button"
          aria-label="Copy: npx mjolnir-qa@latest"
          @click="copyCmd"
        >
          <span class="prompt">$</span>
          <code>npx mjolnir-qa@latest</code>
          <span class="copy">{{ copied ? "copied ✓" : "copy" }}</span>
        </button>

        <!-- Proof above the fold: the real verdict, from the same scan the
             report below renders (plan §4, Phase 3). -->
        <div
          class="vcard"
          data-gauge
          role="img"
          :aria-label="`Worthiness ${scan.score} of ${scan.outOf}, ${scan.verdict}, on a demo repo with ${scan.findings} findings`"
        >
          <div class="vc-ring">
            <svg class="gauge" viewBox="0 0 140 140" aria-hidden="true">
              <circle class="track" cx="70" cy="70" r="54" />
              <circle
                class="fill"
                cx="70"
                cy="70"
                r="54"
                :stroke-dasharray="339.292"
                :stroke-dashoffset="dash"
              />
            </svg>
            <span class="vc-score">{{ score }}</span>
          </div>

          <div class="vc-main">
            <p class="vc-verdict">{{ scan.verdict }}</p>
            <p class="vc-meta">
              {{ scan.score }}/{{ scan.outOf }} · {{ scan.findings }} findings
              on the demo repo
            </p>
          </div>

          <ul class="vc-ded">
            <li v-for="d in scan.deductions" :key="d.severity">
              <b>{{ d.count }}×</b><span>{{ d.severity }}</span
              ><em>−{{ d.points }}</em>
            </li>
          </ul>
        </div>
      </div>
    </section>

    <RuneDivider rune="ᚦ" />

    <!-- ===================== SHOWCASE ===================== -->
    <section class="showcase">
      <div class="show-grid">
        <div class="show-copy" data-reveal>
          <h2>One command. One verdict.</h2>
          <p>
            In CI, the product is a single line. It scans only what the branch
            touched and exits non-zero on new problems — drop it in a PR check
            and you are done.
          </p>
          <div class="mini-cmd">
            <span class="prompt">$</span>
            <code>npx mjolnir-qa@latest --scope changed</code>
          </div>
          <p class="fine">
            Below is the tool's own output on a demo repo — the real reporter,
            as text you can select and copy, nothing trimmed.
          </p>
        </div>
      </div>

      <TerminalReport data-reveal />
    </section>

    <RuneDivider rune="ᛖ" />

    <!-- ===================== EVIDENCE ===================== -->
    <section class="evidence">
      <div class="ev-head" data-reveal>
        <h2>"We prove it" is a system, not a slogan</h2>
        <p>
          Every finding carries an evidence level that sets how much it can cost
          the score. A structural proof and a heuristic hunch are not weighted
          the same, and the tool never dresses one up as the other.
        </p>
      </div>
      <div class="ev-grid">
        <article
          v-for="(e, i) in evidence"
          :key="e.level"
          class="ev"
          data-reveal
          :style="{ '--i': i }"
        >
          <EvidenceBadge :level="e.level" />
          <h3>{{ e.name }}</h3>
          <p>{{ e.body }}</p>
        </article>
      </div>
    </section>

    <RuneDivider rune="ᛗ" />

    <!-- ===================== FEATURES ===================== -->
    <section class="features">
      <h2 class="sect-title" data-reveal>Forged for verification</h2>
      <div class="feat-grid">
        <a
          v-for="(f, i) in features"
          :key="f.title"
          class="feat"
          :href="withBase(f.to)"
          data-reveal
          :style="{ '--i': i }"
        >
          <span class="feat-rune" aria-hidden="true">{{ f.r }}</span>
          <h3>{{ f.title }}</h3>
          <p>{{ f.body }}</p>
          <span class="feat-go" aria-hidden="true">→</span>
        </a>
      </div>
    </section>

    <RuneDivider rune="ᛁ" />

    <!-- ===================== MEASURED, NOT ASSERTED ===================== -->
    <section class="measured" data-reveal>
      <div class="meas-inner">
        <p class="meas-lead">The honest number</p>
        <p class="meas-big">
          <strong>{{ measuredCount }}</strong> of {{ ruleCount }} rules
        </p>
        <p class="meas-body">
          carry a false-positive rate measured against real open-source code (n
          ≥ 10 hand-classified findings). The other
          {{ ruleCount - measuredCount }} ship on the author's estimate — and
          every scan footer, the
          <a :href="withBase('/reference/fp-audit')">audit page</a>, and
          <code>mjolnir rules --unmeasured</code> all tell you which is which.
          Rates are published even when they're ugly: a rule that audits badly
          gets quarantined for it.
        </p>
        <a class="meas-link" :href="withBase('/reference/fp-audit')"
          >See the measured rates →</a
        >
      </div>
    </section>

    <RuneDivider rune="ᚨ" />

    <!-- ================ RULE CATALOG PREVIEW ================ -->
    <CatalogPreview />

    <RuneDivider rune="ᛞ" />

    <!-- ===================== NOT A LINTER ===================== -->
    <section class="compare" data-reveal>
      <h2 class="sect-title">Not another linter</h2>
      <div class="cmp-grid">
        <div class="cmp cmp-them">
          <h3>Linters &amp; coverage tools</h3>
          <p>tell you whether the code follows rules.</p>
          <ul>
            <li>Blind to CI workflow integrity</li>
            <li>One language, one ecosystem</li>
            <li>No sense of whether a run can be trusted</li>
          </ul>
        </div>
        <div class="cmp cmp-us">
          <span class="cmp-mark" aria-hidden="true">ᛏ</span>
          <h3>Mjölnir</h3>
          <p>tells you whether your verification can be trusted.</p>
          <ul>
            <li>Catches false-green CI tricks structurally</li>
            <li>TS · Python · Java · C# from one pass</li>
            <li>Reads real run data for TRUE-FLAKE verdicts</li>
            <li>Measured false-positive rates, published even when ugly</li>
          </ul>
        </div>
      </div>
    </section>

    <!-- ===================== FINAL CTA ===================== -->
    <section class="final" data-reveal>
      <h2>Stop shipping tests you can't trust.</h2>
      <button
        class="cmd big"
        :class="{ copied }"
        type="button"
        aria-label="Copy: npx mjolnir-qa@latest"
        @click="copyCmd"
      >
        <span class="prompt">$</span>
        <code>npx mjolnir-qa@latest</code>
        <span class="copy">{{ copied ? "copied ✓" : "copy" }}</span>
      </button>
      <p class="built">Local-first · zero telemetry · MIT · v0.5.x open beta</p>
    </section>
  </main>
</template>

<style scoped>
.mj {
  --edge: clamp(1.2rem, 5vw, 4rem);
  overflow-x: clip;
}
.mj :where(h2, h3, h4) {
  font-family: var(--mj-display);
  font-weight: 600;
  line-height: 1.2;
  border: 0;
  padding: 0;
}
.mj h2 {
  letter-spacing: 0.01em;
}

/* ---------------- HERO ---------------- */
.hero {
  position: relative;
  min-height: min(76vh, 700px);
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
  padding: 4.4rem var(--edge) 3rem;
  isolation: isolate;
  background: var(--mj-hero-ink);
  color: var(--mj-hero-text);
}
.hero-bg {
  position: absolute;
  inset: 0;
  z-index: -1;
  overflow: hidden;
}
.aurora {
  position: absolute;
  inset: -30%;
  /* Soft radial stops instead of a conic gradient under filter: blur(60px).
     The blur filter forced a full repaint of a viewport-sized layer on
     every frame of the rotation; radial gradients are soft by
     construction, so the rotation is a cheap composited transform
     (plan §4, Phase 4). */
  background:
    radial-gradient(
      closest-side at 34% 36%,
      rgba(201, 162, 57, 0.15),
      transparent 100%
    ),
    radial-gradient(
      closest-side at 68% 54%,
      rgba(69, 212, 196, 0.17),
      transparent 100%
    ),
    radial-gradient(
      closest-side at 50% 80%,
      rgba(92, 196, 224, 0.11),
      transparent 100%
    );
  animation: spin 40s linear infinite;
  will-change: transform;
}
.forge-glow {
  position: absolute;
  left: 50%;
  bottom: -45%;
  width: 120%;
  aspect-ratio: 1;
  transform: translateX(-50%);
  background: radial-gradient(
    circle,
    rgba(230, 189, 87, 0.14),
    rgba(55, 189, 169, 0.06) 45%,
    transparent 72%
  );
  animation: breathe 7s ease-in-out infinite;
}
.bolt {
  position: absolute;
  top: 0;
  right: 7%;
  height: 100%;
  width: 180px;
  opacity: 0.42;
  filter: drop-shadow(0 0 10px rgba(55, 212, 198, 0.5));
  animation: flicker 6s steps(1) infinite;
}
@media (max-width: 860px) {
  .bolt {
    right: -6%;
    opacity: 0.16;
  }
}

.hero-inner {
  max-width: 820px;
  animation: rise 0.9s cubic-bezier(0.2, 0.7, 0.2, 1) both;
}
.hero-logo {
  margin: 0;
  padding: 0;
  border: 0;
  line-height: 0;
  /* bridge the logo art's own navy scene into the hero ground */
  background: radial-gradient(
    ellipse 68% 58% at 50% 46%,
    rgba(20, 33, 46, 0.6),
    transparent 72%
  );
}
.hero-logo img {
  display: block;
  width: min(360px, 74vw);
  height: auto;
  margin: 0 auto;
  filter: drop-shadow(0 12px 46px rgba(7, 12, 20, 0.55))
    drop-shadow(0 0 40px rgba(69, 212, 196, 0.12));
}
.lede {
  font-family: var(--mj-display);
  font-size: clamp(1.15rem, 3.4vw, 1.9rem);
  margin: 1.1rem 0 0;
  color: var(--mj-hero-text);
}
.shimmer {
  /* never split "We prove it." across lines */
  white-space: nowrap;
  background: linear-gradient(
    100deg,
    var(--mj-ember-hot) 0%,
    #fff2d6 20%,
    var(--mj-spark-bright) 40%,
    var(--mj-ember-hot) 60%,
    #fff2d6 80%,
    var(--mj-ember-hot) 100%
  );
  background-size: 300% 100%;
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
  animation: sweep 5s linear infinite;
}
@media (max-width: 560px) {
  /* on a phone, drop it cleanly onto its own line */
  .shimmer {
    display: block;
    margin-top: 0.15rem;
  }
}
.sub {
  max-width: 58ch;
  margin: 1rem auto 0;
  color: var(--mj-hero-muted);
  font-size: 1.02rem;
  line-height: 1.7;
}

.cta-row {
  display: flex;
  gap: 0.9rem;
  justify-content: center;
  flex-wrap: wrap;
  margin-top: 1.7rem;
}
.btn {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.8rem 1.4rem;
  border-radius: 9px;
  font-weight: 600;
  font-size: 0.95rem;
  transition:
    transform 0.16s ease,
    box-shadow 0.16s ease,
    background 0.16s ease;
}
.btn-primary {
  color: #0b0f17;
  background: linear-gradient(180deg, var(--mj-ember-hot), var(--mj-ember));
  box-shadow:
    0 10px 30px -8px rgba(224, 180, 67, 0.6),
    inset 0 1px 0 rgba(255, 255, 255, 0.4);
}
.btn-primary:hover {
  transform: translateY(-2px);
  box-shadow:
    0 16px 40px -8px rgba(224, 180, 67, 0.7),
    inset 0 1px 0 rgba(255, 255, 255, 0.5);
}
.btn-ghost {
  color: var(--mj-hero-text);
  border: 1px solid var(--mj-hero-line);
  background: rgba(255, 255, 255, 0.03);
}
.btn-ghost:hover {
  transform: translateY(-2px);
  border-color: rgba(198, 204, 214, 0.4);
  background: rgba(255, 255, 255, 0.06);
}

.cmd {
  display: inline-flex;
  align-items: center;
  gap: 0.7rem;
  margin-top: 1.2rem;
  padding: 0.65rem 0.7rem 0.65rem 1rem;
  border-radius: 10px;
  border: 1px solid var(--mj-hero-line);
  background: rgba(8, 11, 18, 0.6);
  font-family: var(--vp-font-family-mono);
  font-size: 0.9rem;
  color: var(--mj-hero-text);
  cursor: pointer;
  transition: border-color 0.16s ease;
}
.cmd:hover {
  border-color: rgba(198, 204, 214, 0.35);
}
.cmd .prompt {
  color: var(--mj-ember-hot);
}
.cmd code {
  background: none;
  color: inherit;
  font-size: inherit;
}
.cmd .copy {
  font-size: 0.72rem;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--mj-hero-muted);
  border: 1px solid var(--mj-hero-line);
  border-radius: 6px;
  padding: 0.25rem 0.5rem;
}
.cmd.copied .copy {
  color: var(--mj-ember-hot);
  border-color: rgba(224, 180, 67, 0.5);
}

/* ---------------- SHOWCASE ---------------- */
.showcase {
  max-width: 1080px;
  margin: 0 auto;
  padding: 1rem var(--edge) 2rem;
}
.show-grid {
  display: grid;
  grid-template-columns: 1.3fr 0.7fr;
  gap: clamp(1.5rem, 5vw, 3.5rem);
  align-items: center;
}
.show-copy h2 {
  font-size: clamp(1.6rem, 4vw, 2.3rem);
  margin: 0 0 0.9rem;
}
.show-copy p {
  color: var(--vp-c-text-2);
  line-height: 1.7;
}
.show-copy .fine {
  font-size: 0.9rem;
  color: var(--vp-c-text-3);
}
.mini-cmd,
.mini-cmd code {
  font-family: var(--vp-font-family-mono);
}
.mini-cmd {
  display: inline-flex;
  gap: 0.55rem;
  margin: 1rem 0;
  padding: 0.6rem 0.9rem;
  border-radius: 8px;
  background: var(--vp-c-bg-alt);
  border: 1px solid var(--vp-c-border);
  font-size: 0.86rem;
}
.mini-cmd .prompt {
  color: var(--vp-c-brand-1);
}

.vcard {
  display: grid;
  grid-template-columns: auto 1fr auto;
  align-items: center;
  gap: 1.1rem 1.4rem;
  margin: 1.6rem auto 0;
  padding: 0.9rem 1.2rem;
  max-width: 620px;
  text-align: left;
  border: 1px solid var(--mj-hero-line);
  border-radius: 12px;
  background: rgba(8, 11, 18, 0.55);
  backdrop-filter: blur(6px);
}
.vc-ring {
  position: relative;
  width: 74px;
  aspect-ratio: 1;
  flex: none;
}
.vc-score {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--mj-display);
  font-size: 1.5rem;
  line-height: 1;
  color: var(--mj-hero-text);
  font-variant-numeric: tabular-nums;
}
.vc-main {
  min-width: 0;
}
.vc-verdict {
  font-family: var(--mj-display);
  font-size: 1.05rem;
  letter-spacing: 0.06em;
  margin: 0;
  color: var(--mj-needswork);
}
.vc-meta {
  margin: 0.15rem 0 0;
  font-size: 0.82rem;
  color: var(--mj-hero-muted);
}
.vc-ded {
  list-style: none;
  margin: 0;
  padding: 0;
  display: grid;
  gap: 0.15rem;
  font-family: var(--vp-font-family-mono);
  font-size: 0.74rem;
  color: var(--mj-hero-muted);
}
.vc-ded li {
  display: grid;
  grid-template-columns: 2.4rem 4.6rem 2.4rem;
  gap: 0.35rem;
}
.vc-ded b {
  font-weight: 500;
  color: var(--mj-hero-text);
  text-align: right;
  font-variant-numeric: tabular-nums;
}
.vc-ded em {
  font-style: normal;
  text-align: right;
  color: var(--mj-needswork);
  font-variant-numeric: tabular-nums;
}
.gauge {
  width: 100%;
  height: 100%;
  transform: rotate(-90deg);
}
.gauge .track {
  fill: none;
  stroke: rgba(198, 204, 214, 0.16);
  stroke-width: 9;
}
.gauge .fill {
  fill: none;
  stroke-width: 9;
  stroke-linecap: round;
  stroke: var(--mj-needswork);
  filter: drop-shadow(0 0 8px rgba(224, 180, 67, 0.45));
  transition: stroke-dashoffset 0.1s linear;
}

/* ---------------- SCAN CAPTURE ---------------- */

/* ---------------- EVIDENCE ---------------- */
.evidence {
  max-width: 1000px;
  margin: 0 auto;
  padding: 1rem var(--edge) 2rem;
}
.ev-head {
  text-align: center;
  max-width: 62ch;
  margin: 0 auto 2.4rem;
}
.ev-head h2 {
  font-size: clamp(1.5rem, 4vw, 2.2rem);
  margin: 0 0 0.8rem;
}
.ev-head p {
  color: var(--vp-c-text-2);
  line-height: 1.7;
}
.ev-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 1.1rem;
}
.ev {
  padding: 1.5rem 1.4rem;
  border-radius: 14px;
  background: var(--vp-c-bg-alt);
  border: 1px solid var(--vp-c-border);
}
.ev h3 {
  margin: 0.7rem 0 0.4rem;
  font-family: var(--mj-display);
  font-size: 1.05rem;
}
.ev p {
  margin: 0;
  font-size: 0.9rem;
  line-height: 1.6;
  color: var(--vp-c-text-2);
}

/* ---------------- MEASURED ---------------- */
.measured {
  padding: 1rem var(--edge) 2rem;
}
.meas-inner {
  max-width: 760px;
  margin: 0 auto;
  padding: 2.4rem 2rem;
  border-radius: 16px;
  border: 1px solid rgba(224, 180, 67, 0.3);
  background: linear-gradient(
    180deg,
    rgba(224, 180, 67, 0.09),
    transparent 65%
  );
  text-align: center;
}
.meas-lead {
  font-family: var(--mj-display);
  letter-spacing: 0.22em;
  text-transform: uppercase;
  font-size: 0.75rem;
  color: var(--vp-c-brand-1);
  margin: 0;
}
.meas-big {
  font-family: var(--mj-display);
  font-size: clamp(1.8rem, 6vw, 3rem);
  margin: 0.4rem 0 1rem;
  color: var(--vp-c-text-1);
}
.meas-big strong {
  color: var(--vp-c-brand-1);
}
.meas-body {
  max-width: 58ch;
  margin: 0 auto 1.4rem;
  line-height: 1.75;
  color: var(--vp-c-text-2);
}
.meas-body code {
  font-size: 0.85em;
}
.meas-link {
  font-weight: 600;
  color: var(--vp-c-brand-1);
}

/* ---------------- FEATURES ---------------- */
.features {
  max-width: 1120px;
  margin: 0 auto;
  padding: 1rem var(--edge) 2rem;
}
.sect-title {
  text-align: center;
  font-size: clamp(1.7rem, 4.5vw, 2.6rem);
  margin: 0 0 2.6rem;
}
.feat-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 1.1rem;
}
.feat {
  position: relative;
  display: block;
  padding: 1.6rem 1.5rem 2.4rem;
  border-radius: 14px;
  background: var(--vp-c-bg-alt);
  border: 1px solid var(--vp-c-border);
  overflow: hidden;
  color: inherit;
  transition:
    transform 0.2s ease,
    border-color 0.2s ease,
    box-shadow 0.2s ease;
}
.feat-go {
  position: absolute;
  right: 1.5rem;
  bottom: 1.2rem;
  color: var(--vp-c-brand-1);
  opacity: 0;
  transform: translateX(-6px);
  transition:
    opacity 0.2s ease,
    transform 0.2s ease;
}
.feat:hover .feat-go,
.feat:focus-visible .feat-go {
  opacity: 1;
  transform: none;
}
.feat:focus-visible {
  outline: 2px solid var(--mj-ember-bright);
  outline-offset: 2px;
}
.feat::before {
  content: "";
  position: absolute;
  inset: 0;
  background: radial-gradient(
    240px circle at var(--mx, 50%) var(--my, 0%),
    rgba(224, 180, 67, 0.14),
    transparent 60%
  );
  opacity: 0;
  transition: opacity 0.25s ease;
}
.feat:hover {
  transform: translateY(-4px);
  border-color: rgba(224, 180, 67, 0.4);
  box-shadow: 0 24px 50px -28px rgba(224, 180, 67, 0.4);
}
.feat:hover::before {
  opacity: 1;
}
.feat-rune {
  font-family: var(--mj-display);
  font-size: 1.7rem;
  color: var(--vp-c-brand-1);
  text-shadow: 0 0 20px rgba(224, 180, 67, 0.35);
}
.feat h3 {
  margin: 0.7rem 0 0.4rem;
  font-size: 1.12rem;
  font-family: var(--mj-display);
  font-weight: 600;
}
.feat p {
  margin: 0;
  font-size: 0.92rem;
  line-height: 1.65;
  color: var(--vp-c-text-2);
}

/* ---------------- COMPARE ---------------- */
.compare {
  max-width: 1000px;
  margin: 0 auto;
  padding: 1rem var(--edge) 2rem;
}
.cmp-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1.2rem;
  align-items: start;
}
.cmp {
  padding: 1.7rem 1.6rem;
  border-radius: 14px;
  border: 1px solid var(--vp-c-border);
}
.cmp h3 {
  margin: 0 0 0.2rem;
  font-family: var(--mj-display);
  font-size: 1.1rem;
  font-weight: 600;
}
.cmp > p {
  margin: 0 0 1rem;
  color: var(--vp-c-text-2);
  font-size: 0.92rem;
}
.cmp ul {
  margin: 0;
  padding: 0;
  list-style: none;
}
.cmp li {
  position: relative;
  padding: 0.4rem 0 0.4rem 1.4rem;
  font-size: 0.9rem;
  color: var(--vp-c-text-2);
  border-top: 1px solid var(--vp-c-gutter);
}
.cmp li::before {
  position: absolute;
  left: 0;
  top: 0.4rem;
}
.cmp-them {
  background: var(--vp-c-bg-alt);
}
.cmp-them li::before {
  content: "✕";
  color: var(--vp-c-text-3);
}
.cmp-us {
  position: relative;
  background: linear-gradient(
    180deg,
    rgba(224, 180, 67, 0.08),
    transparent 70%
  );
  border-color: rgba(224, 180, 67, 0.35);
}
.cmp-us li::before {
  content: "ᛏ";
  font-family: var(--mj-display);
  color: var(--vp-c-brand-1);
}
.cmp-mark {
  position: absolute;
  top: 1rem;
  right: 1.2rem;
  font-family: var(--mj-display);
  font-size: 1.6rem;
  color: rgba(224, 180, 67, 0.5);
}

/* ---------------- FINAL ---------------- */
.final {
  text-align: center;
  padding: 4rem var(--edge) 6rem;
  max-width: 780px;
  margin: 0 auto;
}
.final h2 {
  font-size: clamp(1.7rem, 5vw, 2.8rem);
  margin: 0 0 2rem;
}
.cmd.big {
  font-size: 1rem;
  padding: 0.85rem 0.85rem 0.85rem 1.2rem;
  background: var(--mj-forge-950);
}
.built {
  margin-top: 1.6rem;
  font-size: 0.85rem;
  color: var(--vp-c-text-2);
}
.built a {
  color: var(--vp-c-brand-1);
  font-weight: 600;
}

/* reveal */
/* Reveal-on-scroll is progressive enhancement, never a prerequisite for
   reading the page. The starting (hidden) state is gated on `.mj-anim`,
   which an inline head script in .vitepress/config.mts sets before the
   body paints. No script, no class, no hidden content — previously every
   section below the hero was `opacity: 0` with only JS to undo it, so a
   reader without JS got a hero and nothing else (plan §2, D4). */
.mj-anim [data-reveal] {
  opacity: 0;
  transform: translateY(26px);
  transition:
    opacity 0.7s ease,
    transform 0.7s cubic-bezier(0.2, 0.7, 0.2, 1);
}
.mj-anim [data-reveal].is-in {
  opacity: 1;
  transform: none;
}
.mj-anim .feat[data-reveal] {
  transition-delay: calc(var(--i) * 80ms);
}

/* ---------------- keyframes ---------------- */
/* ---------------- runefield ---------------- */
/* The old rune field drifted forever (`floaty`, one more infinite
   animation on top of four). These settle once and then hold: the motion
   budget Check 5 enforces is unchanged at 4, and a reader who arrives
   mid-scroll sees the same still field as everyone else. */
.runefield {
  position: absolute;
  inset: 0;
  overflow: hidden;
}
.rune {
  position: absolute;
  font-family: var(--mj-display);
  line-height: 1;
  color: var(--mj-steel);
  text-shadow: 0 0 26px rgba(69, 193, 212, 0.28);
  user-select: none;
  animation: rune-settle 1.1s cubic-bezier(0.2, 0.7, 0.2, 1) both;
}

@keyframes rune-settle {
  from {
    opacity: 0;
    transform: translateY(14px) scale(0.94);
  }
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
@keyframes breathe {
  0%,
  100% {
    opacity: 0.75;
    transform: translateX(-50%) scale(1);
  }
  50% {
    opacity: 1;
    transform: translateX(-50%) scale(1.06);
  }
}
@keyframes flicker {
  0%,
  100% {
    opacity: 0.15;
  }
  4%,
  8% {
    opacity: 0.7;
  }
  6% {
    opacity: 0.25;
  }
  50% {
    opacity: 0.12;
  }
  52%,
  56% {
    opacity: 0.55;
  }
}
@keyframes rise {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
}
@keyframes sweep {
  to {
    background-position: -300% 0;
  }
}

/* On a phone the hero is taller than the screen, so the order decides
   what a reader sees first. Proof goes above the explanation: lockup,
   claim, verdict card, actions — and the descriptive paragraph after
   them (plan §4, Phase 3 exit gate at 390x844). */
@media (max-width: 640px) {
  .hero {
    padding: 3.6rem var(--edge) 2.4rem;
  }
  .hero-inner {
    display: flex;
    flex-direction: column;
  }
  .hero-logo {
    order: 1;
  }
  .lede {
    order: 2;
  }
  .vcard {
    order: 3;
    margin-top: 1.3rem;
  }
  .cta-row {
    order: 4;
    margin-top: 1.3rem;
  }
  .cmd {
    order: 5;
    align-self: center;
  }
  .sub {
    order: 6;
    margin-top: 1.5rem;
  }
}

/* The three-column card folds to two, with the deduction table on its
   own full-width row rather than squeezed into a third column. */
@media (max-width: 560px) {
  .vcard {
    grid-template-columns: auto 1fr;
    gap: 0.7rem 1rem;
    padding: 0.85rem 1rem;
  }
  .vc-ded {
    grid-column: 1 / -1;
    border-top: 1px solid var(--mj-hero-line);
    padding-top: 0.6rem;
  }
  .vc-ded li {
    grid-template-columns: 2.2rem 1fr 2.4rem;
  }
}

@media (max-width: 820px) {
  .show-grid,
  .cmp-grid {
    grid-template-columns: 1fr;
  }
}
@media (prefers-reduced-motion: reduce) {
  .aurora,
  .forge-glow,
  .bolt,
  .shimmer,
  .rune {
    animation: none !important;
  }
  .mj-anim [data-reveal] {
    opacity: 1;
    transform: none;
    transition: none;
  }
}
</style>
