export const CLI_COMMAND_NAMES = [
  "scan",
  "suppressions",
  "forensics",
  "triage",
  "mutation",
  "badge",
  "trust-report",
  "debt",
  "impact",
  "trend",
  "exec-report",
  "policy",
  "analyze",
  "ci-adapter",
  "dashboard",
  "baseline",
  "diff",
  "verify",
  "pr-comment",
  "summary",
  "stats",
  "fix",
  "create-rule",
  "handover",
  "init",
  "pw-report",
  "doctor",
  "release-trust",
  "rules",
  "explain",
  "doctor:playwright",
  "why",
  "handoff",
  "install",
  "ci-integrity",
  "framework-maturity",
  "suppression-gate",
  "cross-file",
  "contract-verify",
  "trust-trend",
  "evidence-graph",
  "ci",
  "mcp",
  "help",
] as const;

export const CLI_NON_SCAN_COMMANDS: ReadonlySet<string> = new Set(
  CLI_COMMAND_NAMES.filter((command) => command !== "scan"),
);
