/**
 * Agentic QA provenance (Verification Trust Evolution Plan §17).
 *
 * Static provenance markers, EXTRACTED not invented — every marker
 * below is a verifiable real-world convention:
 *   - `generated-marked`: the industry-wide generated-file header
 *     comment ("auto-generated" / "generated by" / "do not edit") in
 *     the file's first lines. Generative tools — AI agents included —
 *     that follow the convention are detected; tools that do not mark
 *     their output are NOT detectable statically.
 *   - `codegen-like`: Playwright codegen names its first recorded test
 *     exactly "test" (`test('test', async ({ page }) => {`), emitting a
 *     linear goto/click script with no assertions. That default title
 *     is the recorder's fingerprint.
 *   - `healed` / MCP-originated: healing and MCP tools emit the SAME
 *     recorder shape (and may carry generated-file headers); there is
 *     NO statically verifiable marker that distinguishes a healed edit
 *     from a hand-edit. Claiming one would be fabrication — the
 *     classifier therefore returns `unmarked` for everything without a
 *     real marker, and the profile says so.
 *
 * HONESTY BOUNDARY (plan §17.4 — same evidence standard regardless of
 * author): the profile is PROVENANCE METADATA ONLY. It never changes
 * scoring, evidence levels, tier caps, or rule behavior — an AI-written
 * test earns trust through exactly the same evidence as a human one.
 * Absence of a marker does NOT prove human authorship.
 */

import type { Finding } from "../types.js";

export type FileProvenance = "unmarked" | "generated-marked" | "codegen-like";

/**
 * Agentic Trust Profile (plan §17.2): per-scan provenance shares +
 * the trust-relevant split of findings across authorship surfaces.
 * All shares are over the DETECTED subset — the note carries the
 * boundary.
 */
export interface AgenticTrustProfile {
  /** Test files scanned (non-workflow). */
  testFiles: number;
  /** Files carrying a generated-file header comment. */
  generatedMarkedFiles: number;
  /** Files matching the Playwright codegen fingerprint. */
  codegenLikeFiles: number;
  /** generatedMarkedFiles / testFiles (0..1). */
  shareMarkedGenerated: number;
  /** Findings inside files with a detected generative marker. */
  findingsInGeneratedFiles: number;
  /** Findings inside files with no detected marker. */
  findingsInUnmarkedFiles: number;
  note: string;
}

const GENERATED_HEADER_RE =
  /^\s*(?:\/\/|#|\/\*)\s*(?:auto[- ]?generated|generated by|do not edit)/i;

/**
 * Codegen fingerprint: the recorder names its first test exactly
 * "test" (and successive recordings "test 1", "test 2"). Verified
 * against `npx playwright codegen` output — the emitted title is
 * `'test'` with no project context.
 */
const CODEGEN_DEFAULT_TITLE_RE =
  /\b(?:test|it)\s*\(\s*['"]test(?:\s+\d+)?['"]\s*,/;

/** Classify one file's provenance. Pure. */
export function classifyProvenance(file: {
  text: string;
  codeText?: string;
}): FileProvenance {
  const header = file.text.slice(0, 600);
  if (GENERATED_HEADER_RE.test(header)) return "generated-marked";
  const source = file.codeText ?? file.text;
  if (CODEGEN_DEFAULT_TITLE_RE.test(source)) return "codegen-like";
  return "unmarked";
}

/**
 * Compute the profile over the scanned test files (per-file provenance
 * collected during the scan's file loop) and the final finding set.
 * Pure; the result is presentation metadata only (§17.4).
 */
export function computeAgenticProfile(
  files: ReadonlyArray<{ path: string; provenance: FileProvenance }>,
  findings: readonly Finding[],
): AgenticTrustProfile {
  const testFiles = files.length;
  const generatedMarkedFiles = files.filter(
    (f) => f.provenance === "generated-marked",
  ).length;
  const codegenLikeFiles = files.filter(
    (f) => f.provenance === "codegen-like",
  ).length;
  const generatedPaths = new Set(
    files.filter((f) => f.provenance !== "unmarked").map((f) => f.path),
  );
  let findingsInGeneratedFiles = 0;
  let findingsInUnmarkedFiles = 0;
  for (const f of findings) {
    if (generatedPaths.has(f.file)) findingsInGeneratedFiles++;
    else findingsInUnmarkedFiles++;
  }
  return {
    testFiles,
    generatedMarkedFiles,
    codegenLikeFiles,
    shareMarkedGenerated:
      testFiles === 0 ? 0 : generatedMarkedFiles / testFiles,
    findingsInGeneratedFiles,
    findingsInUnmarkedFiles,
    note: "Static provenance markers only (generated-file headers, Playwright codegen default titles). Absence of a marker does not prove human authorship; healed and MCP-edited files without markers are indistinguishable from hand-written ones. Provenance never changes scoring or evidence — authorship is metadata, not trust.",
  };
}
