/**
 * The concept vocabulary — 60 concepts covering 79 rules.
 *
 * GENERATED by `scripts/generate-concepts.ts`, COMMITTED for review, and
 * VERIFIED by `tests/contract/certification-concepts.spec.ts`, which fails
 * when the registry moves and this does not. The registry is the authority;
 * this is a claim about it that a reader can check, and the diff when a rule is
 * added is the place that claim is made.
 *
 * ## Why one concept per distinct title
 *
 * A concept is a failure MODE; a rule is a failure mode in one language and one
 * framework. `QA-TEST-004` ("Hard sleep in test", TypeScript) and `QA-PY-005`
 * ("time.sleep() in test", Python) are different rules for the same concept,
 * and the plan's §6 contract is per `concept × language × framework` — so the
 * concept has to be the thing they share or every cell is counted twice.
 *
 * The titles in this tree already assert that grouping, which is why the
 * derivation is mechanical rather than editorial: a rule's title names the
 * failure it detects.
 *
 * ## Why 60 and not the plan's 32
 *
 * The plan's concepts are COARSER. It calls `test-cannot-fail` one concept and
 * the tree calls it five ("Test without assertions", "Empty test body", "Skipped
 * test", "Focused test committed", "Disabled test"). Both are defensible and
 * they measure different things: a coarse concept certifies "a test here can
 * silently pass", a fine one certifies "this detector, in this language,
 * detects this shape".
 *
 * This table is the FINE cut, because it is the one the tree supports without
 * an editorial decision about which detectors are morally the same. The coarse
 * groupings are expressible as a VIEW over it — a concept-to-concept map —
 * which is additive and reviewable, where merging two rows here is not.
 *
 * ## What a concept is NOT
 *
 * It is not a severity, not a tier, and not a support claim. `CERTIFIED` on a
 * CELL means the §6 contract passed for one concept × language × framework; the
 * manifest's `CERTIFIED` means the engine can ANALYSE an ecosystem. Two
 * different words for two different claims, in two different fields.
 */

/** One concept: the rules that implement it, and where they apply. */
export interface Concept {
  /** The failure mode, as the rules name it. */
  readonly title: string;
  /** Every live rule implementing this concept. The §2 `(oldRuleId, legacyArm)` key. */
  readonly rules: readonly string[];
  /** Languages a live rule claims. Empty means the rule declares none. */
  readonly languages: readonly string[];
  /** Frameworks a live rule claims, when it narrows below the language. */
  readonly frameworks: readonly string[];
}

export const CONCEPTS: Readonly<Record<string, Concept>> = {
  "always-success-step-masks-failures": {
    title: "Always-success step masks failures",
    rules: ["QA-CI-008"],
    languages: ["groovy", "yaml"],
    frameworks: ["azure-pipelines", "github-actions", "jenkins"],
  },
  "assertion-in-promise-chain-that-is-never-awaited": {
    title: "Assertion in promise chain that is never awaited",
    rules: ["QA-TQUAL-009"],
    languages: ["javascript", "typescript"],
    frameworks: ["jest", "playwright", "vitest"],
  },
  "bare-truthiness-assert-on-complex-object": {
    title: "Bare truthiness assert on complex object",
    rules: ["QA-PY-004"],
    languages: ["python"],
    frameworks: ["pytest"],
  },
  "blanket-route-mock": {
    title: "Blanket route mock",
    rules: ["QA-PW-142"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "brittle-selector-instead-of-role-based-locator": {
    title: "Brittle selector instead of role-based locator",
    rules: ["QA-CS-106", "QA-JV-106", "QA-PW-004", "QA-PY-104"],
    languages: ["csharp", "java", "javascript", "python", "typescript"],
    frameworks: [
      "junit",
      "mstest",
      "nunit",
      "playwright",
      "pytest-playwright",
      "testng",
      "xunit",
    ],
  },
  "browser-state-shared-across-tests": {
    title: "Browser state shared across tests",
    rules: ["QA-CS-104", "QA-JV-104", "QA-PY-106"],
    languages: ["csharp", "java", "python"],
    frameworks: [
      "junit",
      "mstest",
      "nunit",
      "playwright",
      "pytest",
      "testng",
      "xunit",
    ],
  },
  "commented-out-test": {
    title: "Commented-out test",
    rules: ["QA-PY-009", "QA-TQUAL-011"],
    languages: ["javascript", "python", "typescript"],
    frameworks: ["jest", "playwright", "pytest", "vitest"],
  },
  "config-retry-worker-abuse": {
    title: "Config retry/worker abuse",
    rules: ["QA-PW-121"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "continue-on-error-masks-a-failing-verification-gate": {
    title: "continue-on-error masks a failing verification gate",
    rules: ["QA-CI-001"],
    languages: ["yaml"],
    frameworks: ["azure-pipelines", "github-actions"],
  },
  "css-xpath-string-selector-instead-of-a-normalized-locator": {
    title: "CSS/XPath string selector instead of a normalized locator",
    rules: ["QA-PW-146"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "cypress-config-disables-chromewebsecurity": {
    title: "Cypress config disables chromeWebSecurity",
    rules: ["QA-CYP-003"],
    languages: ["javascript", "typescript"],
    frameworks: ["cypress"],
  },
  "debug-artifact-committed-to-e2e-spec": {
    title: "Debug artifact committed to e2e spec",
    rules: ["QA-PW-003"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "describe-serial-without-justification": {
    title: "describe.serial without justification",
    rules: ["QA-PW-117"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "disabled-test": {
    title: "Disabled test",
    rules: ["QA-JV-101"],
    languages: ["java"],
    frameworks: ["junit", "testng"],
  },
  "empty-test-body": {
    title: "Empty test body",
    rules: ["QA-TEST-010"],
    languages: ["javascript", "typescript"],
    frameworks: ["jest", "mocha", "playwright", "vitest"],
  },
  "environment-coupling-in-test": {
    title: "Environment coupling in test",
    rules: ["QA-ENV-001"],
    languages: ["javascript", "typescript"],
    frameworks: ["jest", "playwright", "vitest"],
  },
  "fixed-cy-wait-n-hard-coded-wait": {
    title: "Fixed cy.wait(n) hard-coded wait",
    rules: ["QA-CYP-001"],
    languages: ["javascript", "typescript"],
    frameworks: ["cypress"],
  },
  "focused-test-committed": {
    title: "Focused test committed",
    rules: ["QA-PY-001", "QA-TEST-001"],
    languages: ["javascript", "python", "typescript"],
    frameworks: ["jest", "mocha", "playwright", "pytest", "vitest"],
  },
  "focused-test-only": {
    title: "Focused test (.only)",
    rules: ["QA-CYP-002"],
    languages: ["javascript", "typescript"],
    frameworks: ["cypress"],
  },
  "framelocator-chain-deeper-than-2": {
    title: "frameLocator chain deeper than 2",
    rules: ["QA-PW-113"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "global-setup-mutating-shared-state": {
    title: "Global setup mutating shared state",
    rules: ["QA-PW-125"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "hard-sleep-before-element-lookup": {
    title: "Hard sleep before element lookup",
    rules: ["QA-SE-001", "QA-SE-002", "QA-SE-003"],
    languages: ["csharp", "java", "python"],
    frameworks: ["selenium"],
  },
  "hard-sleep-in-test": {
    title: "Hard sleep in test",
    rules: ["QA-CS-102", "QA-JV-102", "QA-TEST-004"],
    languages: ["csharp", "java", "javascript", "typescript"],
    frameworks: [
      "jest",
      "junit",
      "mocha",
      "mstest",
      "nunit",
      "playwright",
      "testng",
      "vitest",
      "xunit",
    ],
  },
  "hard-sleep-via-waitfortimeout": {
    title: "Hard sleep via waitForTimeout",
    rules: ["QA-PW-101"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "hardcoded-environment-url-in-spec": {
    title: "Hardcoded environment URL in spec",
    rules: ["QA-PW-123"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "hardcoded-url-in-test": {
    title: "Hardcoded URL in test",
    rules: ["QA-PY-108"],
    languages: ["python"],
    frameworks: ["pytest"],
  },
  "ignored-exit-code-true": {
    title: "Ignored exit code (|| true)",
    rules: ["QA-CI-002"],
    languages: ["groovy", "yaml"],
    frameworks: ["azure-pipelines", "github-actions", "jenkins"],
  },
  "load-event-wait-instead-of-web-first-assertion": {
    title: "Load-event wait instead of web-first assertion",
    rules: ["QA-PW-102"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "mutable-fixture-shared-across-tests": {
    title: "Mutable fixture shared across tests",
    rules: ["QA-PY-011"],
    languages: ["python"],
    frameworks: ["pytest"],
  },
  "no-screenshot-video-capture-on-failure": {
    title: "No screenshot/video capture on failure",
    rules: ["QA-PW-143"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "no-smoke-regression-project-split": {
    title: "No smoke/regression project split",
    rules: ["QA-PW-124"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "no-trace-capture-on-retry": {
    title: "No trace capture on retry",
    rules: ["QA-PW-122"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "playwright-codegen-default-test-title-recording-artifact": {
    title: "Playwright codegen default test title (recording artifact)",
    rules: ["QA-PW-147"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "playwright-test-without-assertions": {
    title: "Playwright test without assertions",
    rules: ["QA-PY-105"],
    languages: ["python"],
    frameworks: ["playwright", "pytest-playwright"],
  },
  "pytest-raises-without-match": {
    title: "pytest.raises without match",
    rules: ["QA-PY-007"],
    languages: ["python"],
    frameworks: ["pytest"],
  },
  "report-consumed-but-never-generated": {
    title: "Report consumed but never generated",
    rules: ["QA-CI-005"],
    languages: ["yaml"],
    frameworks: ["github-actions"],
  },
  "retries-configured-without-a-flake-triage-loop": {
    title: "Retries configured without a flake-triage loop",
    rules: ["QA-PW-141"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "retry-abuse-hiding-flakiness": {
    title: "Retry abuse hiding flakiness",
    rules: ["QA-TEST-006"],
    languages: ["javascript", "typescript"],
    frameworks: ["jest", "mocha", "playwright", "vitest"],
  },
  "retry-masks-test-failures": {
    title: "Retry masks test failures",
    rules: ["QA-CI-007", "QA-CS-109", "QA-JV-109"],
    languages: ["csharp", "java", "yaml"],
    frameworks: [
      "azure-pipelines",
      "github-actions",
      "junit",
      "mstest",
      "nunit",
      "testng",
      "xunit",
    ],
  },
  "screenshot-without-maxdiffpixelratio": {
    title: "Screenshot without maxDiffPixelRatio",
    rules: ["QA-PW-140"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "shared-page-object-across-tests": {
    title: "Shared page object across tests",
    rules: ["QA-PW-115"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "single-browser-project-matrix": {
    title: "Single-browser project matrix",
    rules: ["QA-PW-144"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "skipped-test": {
    title: "Skipped test",
    rules: ["QA-CS-101", "QA-PY-002", "QA-TEST-002"],
    languages: ["csharp", "javascript", "python", "typescript"],
    frameworks: [
      "jest",
      "mocha",
      "mstest",
      "nunit",
      "pytest",
      "vitest",
      "xunit",
    ],
  },
  "storagestate-without-expiry-strategy": {
    title: "storageState without expiry strategy",
    rules: ["QA-PW-116"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "sync-async-playwright-api-mix": {
    title: "Sync/async Playwright API mix",
    rules: ["QA-PY-101"],
    languages: ["python"],
    frameworks: ["playwright", "pytest-playwright"],
  },
  "tautological-assertion": {
    title: "Tautological assertion",
    rules: ["QA-PY-012", "QA-TQUAL-002"],
    languages: ["javascript", "python", "typescript"],
    frameworks: ["jest", "playwright", "pytest", "vitest"],
  },
  "test-command-does-not-propagate-exit-code": {
    title: "Test command does not propagate exit code",
    rules: ["QA-CI-009"],
    languages: ["groovy", "yaml"],
    frameworks: ["github-actions", "jenkins"],
  },
  "test-function-with-no-assertions": {
    title: "Test function with no assertions",
    rules: ["QA-PY-003"],
    languages: ["python"],
    frameworks: ["pytest"],
  },
  "test-with-no-assertions": {
    title: "Test with no assertions",
    rules: ["QA-TEST-003"],
    languages: ["javascript", "typescript"],
    frameworks: ["jest", "mocha", "playwright", "vitest"],
  },
  "test-without-assertions": {
    title: "Test without assertions",
    rules: ["QA-CS-103", "QA-JV-103"],
    languages: ["csharp", "java"],
    frameworks: ["junit", "mstest", "nunit", "testng", "xunit"],
  },
  "tests-skipped-where-they-must-block": {
    title: "Tests skipped where they must block",
    rules: ["QA-CI-010"],
    languages: ["yaml"],
    frameworks: ["github-actions"],
  },
  "time-sleep-in-test": {
    title: "time.sleep() in test",
    rules: ["QA-PY-005"],
    languages: ["python"],
    frameworks: ["pytest"],
  },
  "trial-true-click-without-follow-up-assertion": {
    title: "trial:true click without follow-up assertion",
    rules: ["QA-PW-104"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "try-catch-swallows-a-verification-stage-failure": {
    title: "try/catch swallows a verification-stage failure",
    rules: ["QA-CI-014"],
    languages: ["groovy"],
    frameworks: ["jenkins"],
  },
  "unawaited-playwright-assertion": {
    title: "Unawaited Playwright assertion",
    rules: ["QA-PW-002"],
    languages: ["javascript", "typescript"],
    frameworks: ["playwright"],
  },
  "verification-gate-conditioned-so-it-can-never-fail-the-pipeline": {
    title: "Verification gate conditioned so it can never fail the pipeline",
    rules: ["QA-CI-013"],
    languages: ["yaml"],
    frameworks: ["azure-pipelines"],
  },
  "wait-for-timeout-as-sync": {
    title: "wait_for_timeout() as sync",
    rules: ["QA-PY-103"],
    languages: ["python"],
    frameworks: ["playwright", "pytest-playwright"],
  },
  "waitforloadstate-networkidle-used": {
    title: "waitForLoadState(networkidle) used",
    rules: ["QA-CS-107", "QA-JV-107", "QA-PY-107"],
    languages: ["csharp", "java", "python"],
    frameworks: [
      "junit",
      "mstest",
      "nunit",
      "playwright",
      "pytest",
      "testng",
      "xunit",
    ],
  },
  "waitfortimeout-hard-sleep": {
    title: "waitForTimeout hard sleep",
    rules: ["QA-JV-105"],
    languages: ["java"],
    frameworks: ["junit", "playwright", "testng"],
  },
  "waitfortimeoutasync-hard-sleep": {
    title: "WaitForTimeoutAsync hard sleep",
    rules: ["QA-CS-105"],
    languages: ["csharp"],
    frameworks: ["mstest", "nunit", "playwright", "xunit"],
  },
};

export const CONCEPT_IDS: readonly string[] = Object.keys(CONCEPTS).sort();

/** ruleId → the concepts that claim it. A rule may serve more than one. */
export const CONCEPTS_BY_RULE: ReadonlyMap<string, readonly string[]> = (() => {
  const index = new Map<string, string[]>();
  for (const concept of CONCEPT_IDS) {
    for (const rule of CONCEPTS[concept]?.rules ?? []) {
      const list = index.get(rule) ?? [];
      list.push(concept);
      index.set(rule, list);
    }
  }
  for (const list of index.values()) list.sort();
  return index;
})();

/**
 * The concept a rule implements, or `undefined` when no live rule claims it.
 *
 * `undefined` is the interesting value: it is what a RETIRED rule returns, and
 * §6.4 requires a retired rule's verdicts to re-attach through
 * `(oldRuleId, legacyArm)` rather than silently dropping them. A rule that
 * exists in the registry and in no concept is a gate failure, not a fallback.
 */
export function conceptOf(ruleId: string): string | undefined {
  const claims = CONCEPTS_BY_RULE.get(ruleId);
  return claims === undefined || claims.length === 0 ? undefined : claims[0];
}
