/**
 * `mjolnir policy` — Policy-as-Code (TL-2).
 *
 * Manages team-level quality policies: declare required rules, gate CI
 * on custom criteria, manage repo-level overrides.
 *
 * Subcommands:
 *   init     — create a team policy template
 *   validate — validate a policy file against schema
 *   check    — check scan results against policy gates
 */

import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { writeFileAtomic } from "../lib/fs-atomic.js";
import { join } from "node:path";

import { runScan } from "../engine/scan-pipeline.js";
import { internalErrorMessage, type Output } from "../cli-io.js";
import {
  EXIT_CLEAN,
  EXIT_FINDINGS,
  EXIT_INTERNAL,
  EXIT_USAGE,
} from "../exit-codes.js";

export interface PolicyGates {
  requiredRules: string[];
  forbiddenSeverities: Record<string, "block" | "advisory" | "report">;
  maxFindings: number | null;
  minScore: number | null;
}

export interface PolicyFile {
  version: 1;
  name: string;
  description: string;
  gates: PolicyGates;
}

export function defaultPolicy(name: string = "team-policy"): PolicyFile {
  return {
    version: 1,
    name,
    description:
      "Team quality policy — auto-generated by mjolnir policy --init",
    gates: {
      requiredRules: [],
      forbiddenSeverities: {
        error: "block",
        warning: "advisory",
        info: "report",
      },
      maxFindings: null,
      minScore: null,
    },
  };
}

export function validatePolicy(policy: unknown): string[] {
  const errors: string[] = [];
  if (typeof policy !== "object" || policy === null) {
    errors.push("Policy must be an object");
    return errors;
  }
  const p = policy as Record<string, unknown>;
  if (p.version !== 1) errors.push(`Unsupported version: ${String(p.version)}`);
  if (typeof p.name !== "string") errors.push("Missing or invalid 'name'");
  if (typeof p.gates !== "object" || p.gates === null)
    errors.push("Missing or invalid 'gates'");
  const gates = p.gates as Record<string, unknown> | undefined;
  if (!Array.isArray(gates?.requiredRules))
    errors.push("'gates.requiredRules' must be an array");
  return errors;
}

export async function runPolicyCommand(
  argv: string[],
  io: { out: Output; err: Output },
): Promise<number> {
  const subcommand = argv[0] ?? "init";
  const target = argv.slice(1).find((a) => !a.startsWith("-")) ?? ".mjolnir";

  if (subcommand === "init") {
    const policyPath = join(target, "mjolnir.policy.json");
    const policy = defaultPolicy();
    const dir = target === ".mjolnir" ? target : ".";
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    // Atomic (audit S9): the policy file is a gate input. A truncated write
    // left Mj�lnir reading a half-parsed policy, which then silently applied
    // fewer rules than the user configured.
    writeFileAtomic(policyPath, JSON.stringify(policy, null, 2) + "\n");
    io.out(`Policy written to ${policyPath}`);
    io.out(`Use 'mjolnir policy validate ${policyPath}' to validate.`);
    io.out(
      `Use 'mjolnir policy check <target> --policy ${policyPath}' to check results.`,
    );
    return EXIT_CLEAN;
  }

  if (subcommand === "validate") {
    const policyPath =
      argv.slice(1).find((a) => !a.startsWith("-")) ??
      join(target, "mjolnir.policy.json");
    if (!existsSync(policyPath)) {
      io.err(`Policy file not found: ${policyPath}`);
      return EXIT_USAGE;
    }
    try {
      const raw = JSON.parse(readFileSync(policyPath, "utf8")) as unknown;
      const errors = validatePolicy(raw);
      if (errors.length === 0) {
        io.out(`Policy is valid (${policyPath})`);
        return EXIT_CLEAN;
      } else {
        io.err(`Policy validation errors:`);
        for (const e of errors) {
          io.err(`  - ${e}`);
        }
        return EXIT_FINDINGS;
      }
    } catch (e) {
      internalErrorMessage(e, io.err, false);
      return EXIT_INTERNAL;
    }
  }

  if (subcommand === "check") {
    const scanTarget = argv.slice(1).find((a) => !a.startsWith("-")) ?? ".";
    const policyIdx = argv.indexOf("--policy");
    const policyPath =
      policyIdx !== -1
        ? (argv[policyIdx + 1] ?? "")
        : join(target, "mjolnir.policy.json");

    if (!existsSync(scanTarget)) {
      io.err(`Scan target does not exist: ${scanTarget}`);
      return EXIT_USAGE;
    }
    if (!existsSync(policyPath)) {
      io.err(
        `Policy file not found: ${policyPath}. Run 'mjolnir policy init' first.`,
      );
      return EXIT_USAGE;
    }

    try {
      const raw = readFileSync(policyPath, { encoding: "utf8" });
      const policy: PolicyFile = JSON.parse(raw) as PolicyFile;
      const result = await runScan({
        target: scanTarget,
        json: true,
        verbose: false,
        maxDurationMs: Number.POSITIVE_INFINITY,
        scopeChanged: false,
        format: "json",
        strict: false,
      });

      const violations: string[] = [];

      for (const ruleId of policy.gates.requiredRules) {
        const found = result.findings.some((f) => f.ruleId === ruleId);
        if (!found) {
          violations.push(
            `Required rule ${ruleId} has no findings (not triggered)`,
          );
        }
      }

      const _findingErrors = result.findings.filter(
        (f) => f.severity === "error",
      ).length;
      const _findingWarnings = result.findings.filter(
        (f) => f.severity === "warning",
      ).length;

      if (
        policy.gates.maxFindings !== null &&
        result.findings.length > policy.gates.maxFindings
      ) {
        violations.push(
          `Findings ${result.findings.length} exceed max ${policy.gates.maxFindings}`,
        );
      }
      if (
        policy.gates.minScore !== null &&
        (result.score === null || result.score < policy.gates.minScore)
      ) {
        violations.push(
          `Score ${result.score ?? "N/A"} below minimum ${policy.gates.minScore}`,
        );
      }

      if (violations.length === 0) {
        io.out(
          `Policy check PASSED — ${result.findings.length} findings, score ${result.score ?? "N/A"}`,
        );
        return EXIT_CLEAN;
      } else {
        io.out(`Policy check FAILED — ${violations.length} violation(s):`);
        for (const v of violations) {
          io.out(`  ✗ ${v}`);
        }
        return EXIT_FINDINGS;
      }
    } catch (e) {
      internalErrorMessage(e, io.err, false);
      return EXIT_INTERNAL;
    }
  }

  io.err(`Unknown policy subcommand: ${subcommand}`);
  return EXIT_USAGE;
}
