/**
 * `npm run docs:machine-contract` — regenerate docs/machine-contract.md
 * from the MachineContract type's runtime shape. Drift-locked by CI's
 * generated-docs-drift gate: a type/shape change that the committed doc
 * does not describe fails the build, same as rule docs.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  CONTRACT_VERSION,
  ANNOTATIONS_LIMIT,
} from "../src/engine/machine-contract.js";
import type { ScanResult } from "../src/types.js";

const OUT = join(process.cwd(), "docs", "machine-contract.md");

// Extract the runtime shape from a hand-built fixture so the doc is
// generated from REAL field names (not prose that can drift).
const fixture: ScanResult = {
  schemaVersion: 1,
  partial: false,
  score: 96,
  frameworks: ["playwright"],
  frameworkDetectionUnknown: false,
  dimensions: [
    { category: "QA-PW", score: 96, errors: 0, warnings: 1, infos: 0 },
  ],
  findings: [
    {
      ruleId: "QA-PW-101",
      category: "QA-PW",
      severity: "warning",
      confidence: "high",
      findingType: "deterministic-defect",
      qaImpact: "FLAKY-RISK",
      evidenceLevel: "E2",
      detectorRevision: 1,
      file: "tests/a.spec.ts",
      line: 3,
      column: 1,
      message: "hard sleep",
      why: "w",
      fix: "f",
    },
  ],
  analysisStatus: {
    discovery: "complete",
    rules: "complete",
    skippedFiles: 0,
    durationMs: 1234,
  },
};

const shape = (obj: Record<string, unknown>, indent: string): string =>
  Object.entries(obj)
    .map(([k, v]) => {
      const type =
        v === null
          ? "null"
          : typeof v === "number"
            ? "number"
            : typeof v === "string"
              ? v.startsWith("sha256:") || k === "digest"
                ? "string"
                : "string (enum'd)"
              : typeof v === "boolean"
                ? "boolean"
                : Array.isArray(v)
                  ? "array"
                  : typeof v === "object"
                    ? "object"
                    : "unknown";
      if (typeof v === "object" && v !== null && !Array.isArray(v)) {
        return `${indent}- \`${k}\` (${type}):\n${shape(v as Record<string, unknown>, indent + "  ")}`;
      }
      return `${indent}- \`${k}\` (${type})`;
    })
    .join("\n");

// Real machine-contract projection of the fixture.
async function main(): Promise<void> {
  const { buildMachineContract } =
    await import("../src/engine/machine-contract.js");
  const contract = buildMachineContract(fixture);

  const doc = `# Machine Verification Contract (generated)

> **Generated by \`npm run docs:machine-contract\` — do not edit by hand.**
> Drift-locked: a \`MachineContract\` shape change that this doc does not
> describe fails CI (generated-docs-drift).

\`contractVersion: ${CONTRACT_VERSION}\` — additive-only within
\`schemaVersion: 1\`.

**Source of truth**: \`scan-pipeline → canonical ScanResult →
buildMachineContract\` (Contract D). No consumer may independently
reconstruct semantics.

## What a machine MAY safely conclude

- The listed findings were detected by the named rules at the stated
  \`detectorRevision\`, with the stated evidence/trust/FP metadata.
- \`completeness\` accurately describes the scan's actual coverage.
- \`summary.advisory\` findings (E0) are advisory — reported, never gating.
- \`score\` is a measurement, not a contract.

## What a machine MUST NEVER infer

- A finding's absence does NOT mean it was fixed. Absence requires the
  §15 lifecycle resolution (suppress · exclude · baseline · partial ·
  truncation · crash · revision change · scope change · retirement).
- Suppression does not mean correctness.
- No findings on a \`partial\` scan does not mean no issues.
- Runtime corroboration is evidence, not truth.
- Mutation evidence (\`mutationEvidence\`) is provenance, not truth: a
  survived mutant is code the suite would not notice changing — never a
  claim the finding is proven real. The E1→E2 consolidation it enables
  is BY DERIVATION (docs/RULE-LIFECYCLE.md, master plan P5); a finding's
  \`trustLevel\` never rises from mutation evidence alone.
- Provenance is not trust. Score is not production readiness.

All completeness/trust/lifecycle facts below are machine-readable
fields — no consumer may parse human-rendered text to learn them (§22.1).

## Shape (generated from the runtime fixture)

\`\`\`
contract (object):
${shape(contract as unknown as Record<string, unknown>, "  ")}
\`\`\`

## Annotation limits

- \`annotations\` is capped at ${ANNOTATIONS_LIMIT} entries per check run
  (GitHub limit); \`annotationsTruncated: true\` when the canonical result
  carried more.
- \`summary.digest\` is \`sha256:\` over the canonical JSON of
  {score, partial, analysisStatus, findings(identity+evidence fields)}.
  Presentation text (message/why/fix) is excluded: rewording detector
  prose does not change the digest of identical semantics.

Full catalog: \`mjolnir rules --md\` · Source:
\`src/engine/machine-contract.ts\`
`;

  writeFileSync(OUT, doc);
  console.log(`Wrote ${OUT}`);
}

void main();
