/**
 * `npm run brand:tokens` — emits every machine-consumable brand surface
 * from `src/brand/tokens.ts`.
 *
 * The token module is the source; these files are output. Editing one of
 * them by hand is the defect this script exists to make impossible:
 * before it, the palette lived in six independent copies and exactly one
 * pair of them was checked, which is how the terminal, the architecture
 * diagram and the README badges each ended up with a different idea of
 * what "Mjölnir gold" is.
 *
 * Emits:
 *   assets/brand/tokens.json                    machine surface (any consumer)
 *   site/.vitepress/theme/styles/vars.css       the website's variables
 *
 * `assets/brand/README.md`'s palette table is verified against the
 * tokens rather than rewritten by this script — it is prose with a table
 * in it, not a generated file, and `brand-doctor` rule 5 fails if the
 * table drifts.
 *
 * DETERMINISM. No timestamps, no ordering that depends on a hash map, no
 * environment. Same tokens in → same bytes out, so
 * `tests/contract/brand-tokens-reproducibility.spec.ts` can lock it.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { format, resolveConfig } from "prettier";

import {
  BADGE,
  BRAND,
  CSS_SEMANTIC,
  CSS_TOKENS,
  EVIDENCE,
  HAIRLINE_RGB,
  MOTION,
  PENDING_SITE,
  SCORE,
  STATUS,
  SURFACE,
  TEXT,
  TINT,
  TRUST,
  TRUST_RUNTIME_BOUNDARY,
  TYPOGRAPHY,
} from "../src/brand/tokens.js";

const ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const TOKENS_JSON = join(ROOT, "assets", "brand", "tokens.json");
const VARS_CSS = join(
  ROOT,
  "site",
  ".vitepress",
  "theme",
  "styles",
  "vars.css",
);

/** The header every generated file carries, so no one edits the output. */
const BANNER = [
  "GENERATED by `npm run brand:tokens` from src/brand/tokens.ts.",
  "Do not edit: change the token module and regenerate.",
  "`scripts/brand-doctor.mjs` fails CI if this file drifts from it.",
];

/* ── assets/brand/tokens.json ────────────────────────────────── */

/**
 * Formats through the repository's own Prettier config, so the emitted
 * bytes are the bytes `npm run lint` expects. Without this the generator
 * and the formatter disagree and the drift lock reports a false positive
 * on every run — a gate that cries wolf is a gate people stop reading.
 */
async function formatted(filepath: string, source: string): Promise<string> {
  const config = await resolveConfig(filepath);
  return format(source, { ...config, filepath });
}

export async function buildTokensJson(): Promise<string> {
  const doc = {
    $generated: BANNER,
    brand: BRAND,
    surface: SURFACE,
    text: TEXT,
    status: STATUS,
    score: SCORE,
    evidence: EVIDENCE,
    trust: { ...TRUST, runtimeBoundary: TRUST_RUNTIME_BOUNDARY },
    tint: TINT,
    badge: BADGE,
    typography: TYPOGRAPHY,
    motion: MOTION,
    hairlineRgb: HAIRLINE_RGB,
    // What is left of the convergence debt, published rather than
    // hidden: brand-doctor resolves generator source against this to
    // tell "reads a canonical token" from "still reads a
    // pre-unification value". The terminal and architecture entries are
    // gone because both converged.
    pending: { site: PENDING_SITE },
  };
  return formatted(TOKENS_JSON, `${JSON.stringify(doc, null, 2)}\n`);
}

/* ── site/.vitepress/theme/styles/vars.css ───────────────────── */

/** `--name: value; /* comment *\/` — one declaration, aligned by hand
 * rather than by column so prettier does not fight the generator. */
function decl([name, value, comment]: readonly [
  string,
  string,
  (string | undefined)?,
]): string {
  const line = `  ${name}: ${value.toLowerCase()};`;
  return comment ? `${line} /* ${comment} */` : line;
}

export async function buildVarsCss(): Promise<string> {
  const palette = CSS_TOKENS.map(decl).join("\n");
  const semantic = CSS_SEMANTIC.map(decl).join("\n");
  return formatted(
    VARS_CSS,
    `/**
 * ${BANNER[0]}
 * ${BANNER[1]}
 * ${BANNER[2]}
 *
 * Mjölnir palette — storm-forged. Brushed steel and forge gold under an
 * aurora, over midnight iron. Derived from the logo; see
 * assets/brand/README.md.
 *
 * ONE palette. The site is dark-only (config.mts \`appearance:
 * "force-dark"\`), so there is no light ramp to keep in sync and no
 * second theme to test. That is deliberate: VitePress applies
 * force-dark by adding \`.dark\` from an inline script, which a reader
 * with scripting off never runs — so the dark values live on :root
 * itself, and the page is dark with or without JS.
 */

:root {
  /* ---- brand accent: forge gold ---- */
  --vp-c-brand-1: ${BRAND.goldBright.toLowerCase()};
  --vp-c-brand-2: ${BRAND.gold.toLowerCase()};
  --vp-c-brand-3: ${BRAND.goldDeep.toLowerCase()};
  --vp-c-brand-soft: rgba(230, 189, 87, 0.15);

  /* ---- surface: midnight iron ---- */
  --vp-c-bg: ${SURFACE.ink900.toLowerCase()};
  --vp-c-bg-alt: ${SURFACE.ink850.toLowerCase()};
  --vp-c-bg-soft: ${SURFACE.soft.toLowerCase()};
  --vp-c-bg-elv: ${SURFACE.panel.toLowerCase()};
  --vp-c-text-1: ${TEXT.primary.toLowerCase()};
  --vp-c-text-2: ${TEXT.secondary.toLowerCase()};
  --vp-c-text-3: ${TEXT.muted.toLowerCase()};
  --vp-c-divider: rgba(${HAIRLINE_RGB}, 0.1);
  --vp-c-border: rgba(${HAIRLINE_RGB}, 0.14);
  --vp-c-gutter: rgba(${HAIRLINE_RGB}, 0.06);

  /* ---- type ---- */
  --vp-font-family-base: ${TYPOGRAPHY.sans.stack};
  --vp-font-family-mono: ${TYPOGRAPHY.mono.stack};
  --mj-display: ${TYPOGRAPHY.display.stack};

  /* ---- palette ---- */
${palette}

  /* ---- semantic: verdict, evidence, trust ----
   * Score colors follow the ScoreState model (src/reporter/score-state.ts):
   * critical 0-49 / warning 50-79 / trusted 80-99 / forged 100. Green is
   * not a score color; --mj-ok survives for non-score success only.
   * Trust L0-L2 are static (steel ramp) and L3-L5 require a real run
   * (aurora ramp) — the hue break at L2|L3 is the runtime boundary and
   * every surface that draws the ladder must draw it. */
${semantic}
  --mj-critical: var(--mj-unworthy);
  --mj-warning: var(--mj-needswork);
  --mj-worthy: var(--mj-trusted);
  --mj-forged: linear-gradient(
    90deg,
    ${SCORE.forged.toLowerCase()},
    ${BRAND.goldBright.toLowerCase()}
  );

  /* ---- legacy aliases (kept so existing rules keep resolving) ---- */
  --mj-ember: var(--mj-gold);
  --mj-ember-bright: var(--mj-gold-bright);
  --mj-ember-hot: var(--mj-gold-hot);
  --mj-spark: var(--mj-aurora);
  --mj-spark-bright: var(--mj-aurora-bright);
  --mj-forge-950: var(--mj-ink-950);
  --mj-forge-900: var(--mj-ink-900);
  --mj-forge-850: var(--mj-ink-850);
  --mj-forge-800: var(--mj-ink-800);
  --mj-parchment: var(--mj-steel);
  --mj-iron: var(--mj-steel-dim);

  /* ---- hero ---- */
  --mj-hero-ink: ${PENDING_SITE.heroInk};
  --mj-hero-text: ${TEXT.primary.toLowerCase()};
  --mj-hero-muted: ${PENDING_SITE.heroMuted};
  --mj-hero-line: rgba(${HAIRLINE_RGB}, 0.14);

  --vp-home-hero-name-color: transparent;
  --vp-home-hero-name-background: linear-gradient(
    180deg,
    ${PENDING_SITE.heroNameTop} 6%,
    var(--mj-steel) 40%,
    var(--mj-gold-bright) 92%
  );

  --vp-c-brand-lighter: var(--mj-gold-hot);
  --vp-c-brand-light: var(--mj-gold-bright);
  --vp-c-brand-dark: var(--vp-c-brand-2);
  --vp-c-brand-darker: var(--vp-c-brand-3);
}
`,
  );
}

/* ── main ────────────────────────────────────────────────────── */

export async function writeAll(): Promise<string[]> {
  writeFileSync(TOKENS_JSON, await buildTokensJson(), "utf8");
  writeFileSync(VARS_CSS, await buildVarsCss(), "utf8");
  return [TOKENS_JSON, VARS_CSS];
}

const isMain = process.argv[1]
  ? fileURLToPath(new URL(`file://${process.argv[1].replaceAll("\\", "/")}`))
  : "";
if (isMain.endsWith("generate-brand-tokens.ts")) {
  for (const f of await writeAll()) process.stdout.write(`wrote ${f}\n`);
}
