/**
 * Generates docs/PLAYWRIGHT-CAPABILITIES.md (growth roadmap §12; plan
 * §9 R7 / WI-20): the Playwright capability matrix as a product surface —
 * 12 capabilities × 8 depth columns, every cell explicitly classed (zero
 * UNCLASSIFIED), every "yes" backed by a pointer that
 * `validateCapabilityMatrix` resolves fail-closed.
 *
 * "This — not rule counts — measures Playwright depth." The doc is
 * generated and drift-locked; the agents column is uniformly "no" until
 * R8 ships the Agent Skill, stated rather than implied.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  CAPABILITY_MATRIX,
  DEPTH_COLUMNS,
  validateCapabilityMatrix,
} from "../src/capabilities.js";

const OUT_PATH = join(
  import.meta.dirname,
  "..",
  "docs",
  "PLAYWRIGHT-CAPABILITIES.md",
);

const COLUMN_LABELS: Record<string, string> = {
  detect: "detect?",
  explain: "explain?",
  produceEvidence: "produce evidence?",
  correlateRuntime: "correlate runtime?",
  trustVerdict: "trust verdict?",
  cli: "via CLI?",
  mcp: "via MCP?",
  agents: "to agents?",
};

function cellLabel(
  state: "yes" | "no" | "unsupported",
  evidence: string[] | undefined,
): string {
  if (state === "yes") {
    const refs = (evidence ?? [])
      .map((p) => (/^QA-[A-Z]+-\d{3}$/.test(p) ? `\`${p}\`` : p))
      .join(", ");
    return `yes (${refs})`;
  }
  return state;
}

export function renderCapabilities(root: string): string {
  const validation = validateCapabilityMatrix(root);
  if (!validation.ok) {
    // Fail-closed: never render a claim surface on unresolved pointers.
    throw new Error(
      `capability matrix has unresolved claims:\n${validation.failures.join("\n")}`,
    );
  }
  const lines: string[] = [];
  lines.push("# Playwright Capability Matrix");
  lines.push("");
  lines.push(
    "Generated by `scripts/generate-playwright-capabilities.ts`",
    "(`npm run docs:capabilities`); drift-locked by",
    "tests/contract/playwright-capabilities.spec.ts.",
    "",
  );
  lines.push(
    "Rule counts are marketing; THIS is the depth claim: per capability,",
    "what the engine detects, explains, produces evidence for, correlates",
    "against runtime facts, classifies into a trust verdict, and exposes",
    "via each consumption surface. Every `yes` names its evidence — a",
    "registered rule ID or an in-repo artifact — and the generator is",
    "fail-closed: a claim never renders on a dangling pointer.",
    "",
  );
  lines.push(
    "The `to agents` column is uniformly **no** until R8 ships the",
    "foundational Agent Skill (growth roadmap WI-22) — stated here rather",
    "than implied by silence.",
    "",
  );

  lines.push(
    "| Capability | " +
      DEPTH_COLUMNS.map((c) => COLUMN_LABELS[c]).join(" | ") +
      " |",
  );
  lines.push("| --- | " + DEPTH_COLUMNS.map(() => "---").join(" | ") + " |");
  for (const row of CAPABILITY_MATRIX) {
    const cells = DEPTH_COLUMNS.map((c) =>
      cellLabel(row.cols[c].state, row.cols[c].evidence),
    );
    lines.push(`| ${row.capability} | ${cells.join(" | ")} |`);
  }
  lines.push("");
  lines.push(
    "Claim law: a cell may move `no` → `yes` only in the same change that",
    "ships its evidence pointer (rule, module, or command) — the drift-lock",
    "fails the build otherwise. Claims never exceed proven capability.",
    "",
  );
  return lines.join("\n");
}

/**
 * Prettier-formatted commit render: the committed doc, the drift-lock's
 * fresh render, and `prettier --check` agree byte-for-byte.
 */
export async function renderForCommit(): Promise<string> {
  const root = join(import.meta.dirname, "..");
  const prettier = await import("prettier");
  return prettier.format(renderCapabilities(root), { parser: "markdown" });
}

if (process.argv[1]?.endsWith("generate-playwright-capabilities.ts")) {
  renderForCommit()
    .then((md) => {
      writeFileSync(OUT_PATH, md);
      console.log("Wrote docs/PLAYWRIGHT-CAPABILITIES.md");
    })
    .catch((err) => {
      console.error(err);
      process.exit(20);
    });
}
