/**
 * Emit `src/certification/concepts.ts` from the live rule registry.
 *
 * The table is COMMITTED and reviewable; this script regenerates it, and
 * `tests/contract/certification-concepts.spec.ts` fails when the committed
 * table and the derivation disagree. Neither the table nor the script is the
 * authority alone — the authority is the registry, and the table is a claim
 * about it that a reader can check.
 *
 * Why one concept per distinct normalised title, when the plan says 32:
 * identical titles are the grouping the tree already asserts. `QA-TEST-004`
 * and `QA-PY-005` are both "Hard sleep in test" and are therefore the same
 * failure mode in two languages; a concept that split them would certify the
 * same detector twice and report two cells where there is one. That yields 60
 * concepts rather than 32 because the plan's concepts are COARSER — it calls
 * `test-cannot-fail` one concept and the tree calls it five ("Test without
 * assertions", "Empty test body", "Skipped test", "Focused test", "Disabled
 * test"). The plan's groupings are a LENS over this table, not a disagreement
 * with it, and the count is reported rather than gated — which is the plan's
 * own rule for counts.
 *
 * Run: npx tsx scripts/generate-concepts.ts [--write]
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { RULES } from "../src/rules/index.js";

interface Rule {
  id: string;
  title?: string;
  languages?: string[];
  frameworks?: string[];
}

/** Language qualifiers a rule puts in its own title, e.g. "(Java, missing WebDriverWait)". */
const TITLE_QUALIFIER =
  /\s*\((?:java|c#|csharp|python|cypress|selenium),\s*[^)]*\)\s*$/iu;

const conceptId = (title: string): string =>
  title
    .replace(TITLE_QUALIFIER, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-+|-+$/gu, "");

interface Derived {
  title: string;
  rules: string[];
  languages: string[];
  frameworks: string[];
}

const groups = new Map<string, Derived>();
for (const rule of RULES as unknown as Rule[]) {
  const title = (rule.title ?? "").trim();
  const id = conceptId(title);
  const existing = groups.get(id);
  const languages = new Set(existing?.languages ?? []);
  const frameworks = new Set(existing?.frameworks ?? []);
  for (const l of rule.languages ?? []) languages.add(l);
  for (const f of rule.frameworks ?? []) frameworks.add(f);
  groups.set(id, {
    title: title.replace(TITLE_QUALIFIER, ""),
    rules: [...(existing?.rules ?? []), rule.id],
    languages: [...languages].sort(),
    frameworks: [...frameworks].sort(),
  });
}

const derived = [...groups.entries()]
  .map(([id, v]) => ({
    id,
    title: v.title,
    rules: v.rules.sort(),
    languages: [
      ...(v as unknown as { languages: Set<string> }).languages,
    ].sort(),
    frameworks: [
      ...(v as unknown as { frameworks: Set<string> }).frameworks,
    ].sort(),
  }))
  .sort((a, b) => a.id.localeCompare(b.id));

const rows = derived
  .map((c) => {
    // Every element quoted, and `frameworks` is its OWN property. Appending it
    // after the closing bracket of `languages` produces
    // `languages: ["a"], ["b"]` — two values where one is expected, which is
    // the same shape of mistake as a template literal that escaped itself.
    const langs = c.languages.map((l) => JSON.stringify(l)).join(", ");
    const fws =
      c.frameworks.length > 0
        ? `\n    frameworks: ${JSON.stringify(c.frameworks)},`
        : "";
    return `  ${JSON.stringify(c.id)}: {
    title: ${JSON.stringify(c.title)},
    rules: ${JSON.stringify(c.rules)},
    languages: [${langs}],${fws}
  },`;
  })
  .join("\n");

const FILE = `/**
 * The concept vocabulary — ${derived.length} concepts covering ${RULES.length} rules.
 *
 * GENERATED by \`scripts/generate-concepts.ts\`, COMMITTED for review, and
 * VERIFIED by \`tests/contract/certification-concepts.spec.ts\`, which fails
 * when the registry moves and this does not. The registry is the authority;
 * this is a claim about it that a reader can check, and the diff when a rule is
 * added is the place that claim is made.
 *
 * ## Why one concept per distinct title
 *
 * A concept is a failure MODE; a rule is a failure mode in one language and one
 * framework. \`QA-TEST-004\` ("Hard sleep in test", TypeScript) and \`QA-PY-005\`
 * ("time.sleep() in test", Python) are different rules for the same concept,
 * and the plan's §6 contract is per \`concept × language × framework\` — so the
 * concept has to be the thing they share or every cell is counted twice.
 *
 * The titles in this tree already assert that grouping, which is why the
 * derivation is mechanical rather than editorial: a rule's title names the
 * failure it detects.
 *
 * ## Why ${derived.length} and not the plan's 32
 *
 * The plan's concepts are COARSER. It calls \`test-cannot-fail\` one concept and
 * the tree calls it five ("Test without assertions", "Empty test body", "Skipped
 * test", "Focused test committed", "Disabled test"). Both are defensible and
 * they measure different things: a coarse concept certifies "a test here can
 * silently pass", a fine one certifies "this detector, in this language,
 * detects this shape".
 *
 * This table is the FINE cut, because it is the one the tree supports without
 * an editorial decision about which detectors are morally the same. The coarse
 * groupings are expressible as a VIEW over it — a concept-to-concept map —
 * which is additive and reviewable, where merging two rows here is not.
 *
 * ## What a concept is NOT
 *
 * It is not a severity, not a tier, and not a support claim. \`CERTIFIED\` on a
 * CELL means the §6 contract passed for one concept × language × framework; the
 * manifest's \`CERTIFIED\` means the engine can ANALYSE an ecosystem. Two
 * different words for two different claims, in two different fields.
 */

/** One concept: the rules that implement it, and where they apply. */
export interface Concept {
  /** The failure mode, as the rules name it. */
  readonly title: string;
  /** Every live rule implementing this concept. The §2 \`(oldRuleId, legacyArm)\` key. */
  readonly rules: readonly string[];
  /** Languages a live rule claims. Empty means the rule declares none. */
  readonly languages: readonly string[];
  /** Frameworks a live rule claims, when it narrows below the language. */
  readonly frameworks: readonly string[];
}

export const CONCEPTS: Readonly<Record<string, Concept>> = {
${rows}
};

export const CONCEPT_IDS: readonly string[] = Object.keys(CONCEPTS).sort();

/** ruleId → the concepts that claim it. A rule may serve more than one. */
export const CONCEPTS_BY_RULE: ReadonlyMap<string, readonly string[]> = (() => {
  const index = new Map<string, string[]>();
  for (const concept of CONCEPT_IDS) {
    for (const rule of CONCEPTS[concept]?.rules ?? []) {
      const list = index.get(rule) ?? [];
      list.push(concept);
      index.set(rule, list);
    }
  }
  for (const list of index.values()) list.sort();
  return index;
})();

/**
 * The concept a rule implements, or \`undefined\` when no live rule claims it.
 *
 * \`undefined\` is the interesting value: it is what a RETIRED rule returns, and
 * §6.4 requires a retired rule's verdicts to re-attach through
 * \`(oldRuleId, legacyArm)\` rather than silently dropping them. A rule that
 * exists in the registry and in no concept is a gate failure, not a fallback.
 */
export function conceptOf(ruleId: string): string | undefined {
  const claims = CONCEPTS_BY_RULE.get(ruleId);
  return claims === undefined || claims.length === 0 ? undefined : claims[0];
}
`;

/**
 * `--out <path>` so the drift check can derive into a TEMP file and format it
 * there. It used to run in place and compare stdout, which meant the committed
 * file and the derived text differed by FORMATTING alone and the assertion
 * failed on a file whose content was current — the failure mode that gets a
 * drift check switched off rather than fixed.
 */
const outFlag = process.argv.indexOf("--out");
const outPath =
  outFlag === -1
    ? join(process.cwd(), "src", "certification", "concepts.ts")
    : (process.argv[outFlag + 1] ?? "");
if (outPath === "") {
  console.error("generate-concepts: --out needs a path");
  process.exit(10);
}

if (process.argv.includes("--write")) {
  writeFileSync(outPath, FILE, "utf8");
  console.log(
    `wrote ${outPath} — ${derived.length} concepts, ${RULES.length} rules`,
  );
  process.exit(0);
}

// CHECK MODE compares FORMATTED text on both sides.
//
// `npm run format` rewrites the committed file, so a byte-for-byte comparison
// against raw generator output reports a stale file whose content is current —
// and a drift check that cries wolf is a drift check that gets switched off.
// The repo already has this discipline in `docs:provenance-drift` ("content
// only; baseSha/observedAt/generatedBy excluded") and in the spec; the npm
// entry point has to agree with them or it is the one place the rule is not
// enforced.
{
  const prettier = join(
    process.cwd(),
    "node_modules",
    "prettier",
    "bin",
    "prettier.cjs",
  );
  const format = (text: string): string =>
    execFileSync(process.execPath, [prettier, "--parser", "typescript"], {
      input: text,
      encoding: "utf8",
    });

  const derivedFormatted = format(FILE);
  const committedFormatted = format(readFileSync(outPath, "utf8"));
  if (committedFormatted === derivedFormatted) {
    console.log(
      `${outPath} is current (${derived.length} concepts, formatting aside)`,
    );
    process.exit(0);
  }
  console.log(
    `${outPath} is STALE — regenerate it with \`npm run generate-concepts\`` +
      " and review the diff",
  );
  process.exitCode = 1;
}
